const DICT_URL = process.env.DICT_URL;
const GITHUB_DICT_TOKEN = process.env.GITHUB_DICT_TOKEN;
const GITHUB_DICT_HOST = process.env.GITHUB_DICT_HOST;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;

export { DICT_URL, GITHUB_DICT_HOST, GITHUB_DICT_TOKEN, ACCESS_TOKEN_SECRET };
