export const simpleWord: { [key: string]: string } = {
  一: 'một/một khi/nhất/vừa',
  七: 'bảy/thất',
  三: 'ba/tam',
  上: 'bên trên/lên/trên/trước/thượng',
  下: 'hạ/dưới/xuống/lần',
  不: 'không/bất',
  与: 'cùng/dữ/và/giống như/cho',
  丑: 'xấu/sửu',
  且: 'lại/mà lại/tạm/thả/mà',
  世: 'thế/đời',
  丘: 'đồi',
  业: 'nghiệp/nghề',
  丛: 'bụi/tùng/bụi rậm/hợp/bụi rậm',
  丝: 'tia/tơ/ti',
  丢: 'ném/mất',
  两: 'hai/lượng/lưỡng',
  个: 'cái/người/quả/cá',
  中: 'bên trong/trúng/trung/giữa/trong',
  串: 'xuyên/xuyến/chuỗi',
  临: 'lâm/gặp/trước khi',
  为: 'vì/làm/là/vi/vì là/thành',
  主: 'chủ/chúa',
  举: 'nâng/cử/giơ/cử động',
  乃: 'chính là/nãi/là',
  久: 'lâu/cửu',
  么: 'a/sao',
  乍: 'chợt/sạ',
  乎: 'hồ/tử',
  乏: 'mệt/thiếu/phạp',
  乐: 'vui/mừng/nhạc',
  乓: 'bang/pằng',
  乖: 'ngoan/nghe lời/quai/láu lỉnh/thông minh',
  乘: 'thừa/lợi dụng/thừa lúc/ngồi/cưỡi/nhân/x',
  乙: 'Ất/B',
  乜: 'liếc',
  九: 'chín/cửu',
  乞: 'xin',
  也: 'cũng/vậy/cũng/thì',
  习: 'tập/quen',
  乡: 'hương/thôn quê',
  书: 'sách/thư/viết',
  买: 'mua/mãi/bán',
  乱: 'loạn/bậy',
  乳: 'sữa/nhũ',
  予: 'cho/dư',
  争: 'tranh/tranh giành',
  事: 'sự tình/sự/chuyện',
  二: 'hai/nhị',
  于: 'tại/cho/vu/với/hơn',
  亏: 'thua thiệt/lỗ/thiếu/khuy/mệt/thiếu (thiệt thòi)/thiệt thòi',
  云: 'mây/vân/nói',
  互: 'lẫn nhau/hỗ',
  五: 'năm/ngũ',
  井: 'giếng/tỉnh/井',
  亘: 'triền miên',
  亚: 'á/kém',
  些: 'chút/ta/chút ít/những/nhiều',
  亟: 'cấp bách',
  亡: 'vong/mất',
  亢: 'cang',
  交: 'giao/nộp/đóng',
  亦: 'cũng/diệc',
  产: 'sinh/sản',
  亨: 'hừ/hanh',
  亮: 'sáng/lượng/sáng lên/phát sáng/rộng mở/lên giọng/to tiếng/bày ra/hiện ra',
  亲: 'thân/hôn',
  亳: 'Bặc',
  亵: 'khinh nhờn/dâm loạn/tiết',
  人: 'người/nhân',
  亿: 'ức/trăm triệu',
  什: 'thập/cái',
  仅: 'vẻn vẹn/chỉ',
  仆: 'bộc',
  仇: 'thù',
  今: 'nay/bây giờ/kim',
  介: 'giới/trung gian',
  仍: 'vẫn/dựa theo/nhưng',
  从: 'từ/theo/tòng',
  仑: 'luân',
  仓: 'kho/thương/cabin/chiếm giữ/kho thóc',
  他: 'hắn/nó/khác/她',
  仗: 'cầm/trận',
  付: 'giao',
  仞: 'trượng',
  代: 'thay mặt/đời/thay/đại',
  令: 'khiến/lệnh/làm/làm cho',
  以: 'lấy/dùng/dĩ/với',
  仪: 'nghi/dụng cụ/(dụng cụ)',
  们: 'nhóm/môn/các/cửa/bọn họ',
  仰: 'ngửa/ngưỡng',
  件: 'kiện/món',
  价: 'giá/giới/giá cả',
  任: 'mặc cho/đảm nhiệm/lần/nhiệm/cho dù/Nhậm/nhiệm kỳ',
  份: 'phần/phân/phận',
  仿: 'phảng phất/mô phỏng',
  企: 'mong đợi',
  伏: 'nằm/ẩn náu/phục/nằm sấp',
  伐: 'phạt/chặt',
  休: 'đừng/nghỉ/hưu/thôi',
  伙: 'băng/hỏa',
  会: 'sẽ/biết/lại/hội/chút//回',
  伝: 'vân',
  伞: 'dù/cái dù/tán/ô',
  传: 'truyền/truyện',
  伢: 'trẻ con',
  伤: 'tổn thương/thương',
  伧: 'sinh',
  伫: 'đứng im lặng hồi lâu',
  估: 'đánh giá',
  伱: 'ngươi',
  伷: 'khúc',
  伸: 'duỗi với',
  伺: 'tứ',
  似: 'như/giống như/tự/dường như/tựa như/hình như',
  但: 'nhưng/vậy',
  低: 'thấp',
  住: 'ở/được/lại',
  佑: 'phù hộ/hữu',
  佔: 'chiếm',
  何: 'gì',
  佘: 'xa/xà',
  余: 'dư/hơn',
  佚: 'dật/ẩn',
  佛: 'Phật/phật',
  作: 'làm/tác',
  你: 'ngươi/cậu',
  佩: 'đeo/bội',
  佯: 'dương/giả vờ',
  佳: 'tốt',
  併: 'gồm/đều',
  佷: 'chất',
  佻: 'điệu',
  使: 'làm/dùng/khiến/sử/làm cho/khiến cho/sử (khiến cho)/sứ',
  侃: 'tán gẫu/khản',
  侄: 'điệt/chất',
  侍: 'hầu/tùy tùng',
  供: 'cung cấp/cúng',
  依: 'theo/y theo/dựa vào',
  侥: 'gặp may mắn',
  侦: 'trinh thám',
  侧: 'bên cạnh/trắc/sườn/bên/chếch/phe/nghiêng',
  侬: 'nông/anh',
  侮: 'khinh/khinh miệt',
  便: 'liền/dễ/lại/tiện',
  促: 'gấp rút',
  俏: 'xinh đẹp',
  俐: 'lợi',
  俑: 'tượng/tượng (chôn chung với người chết)',
  俘: 'bắt được/bắt được (tù binh)',
  保: 'bảo đảm/bảo/bảo vệ',
  俟: 'chờ',
  信: 'tin/thư/tín',
  俩: 'hai/lưỡng',
  俭: 'kiệm/cần kiệm',
  修: 'tu/xây/sửa',
  俯: 'cúi/phủ/cúi xuống',
  俱: 'đều',
  俺: 'ta/yêm/ta đây/ore',
  倍: 'lần/bội',
  倏: 'chợt',
  倒: 'ngược lại/ngã/đảo/đổ/lộn/ngược/cũng/rót',
  倔: 'bướng bỉnh',
  倖: 'may',
  倘: 'thảng/nhưng',
  候: 'đợi',
  倚: 'dựa/ỷ',
  借: 'mượn/cho mượn/tá',
  倦: 'mệt mỏi',
  倨: 'ngạo mạn',
  倩: 'thiến/xinh đẹp',
  倭: 'Uy',
  债: 'nợ/khoản nợ/trái',
  值: 'giá trị/gặp/trị giá/trực',
  倾: 'nghiêng/khuynh',
  偃: 'ngã/dừng lại/ngã ngựa',
  假: 'giả/nghỉ',
  偌: 'như vậy',
  偎: 'tựa/ôi',
  偏: 'lệch/lại/thiên',
  偕: 'giai/cùng',
  做: 'làm/tố',
  停: 'ngừng/đình/dừng',
  偶: 'ngẫu/ta/chợt/ngẫu nhiên/thỉnh thoảng/tượng/rối',
  偷: 'trộm/thâu/lén',
  偿: 'thường/bồi thường',
  傍: 'bàng/bên cạnh',
  傻: 'ngốc/sỏa/ngu',
  像: 'giống/tượng/giống như',
  僰: 'Bặc',
  僱: 'mướn',
  僻: 'tịch/tích',
  允: 'đồng ý',
  元: 'nguyên/đồng',
  充: 'mạo xưng/sung/nạp',
  先: 'trước/tiên/trước tiên',
  光: 'quang/chỉ riêng/ánh sáng/sạch/chỉ',
  克: 'khắc/gram',
  免: 'miễn',
  兑: 'đổi/đoái/đoài',
  兕: 'tê giác',
  兜: 'túi/vòng/lượn',
  入: 'nhập/vào/đi vào',
  全: 'toàn/toàn bộ',
  八: 'tám/bát',
  公: 'công/đực',
  六: 'sáu/lục/ngưu',
  兮: 'này',
  关: 'quan/đóng/nhốt/cửa ải',
  其: 'nó/nàng/kỳ/hắn/ngoài/của nó/',
  具: 'cỗ/cụ/có/bày đủ/đủ/đồ/(chiếc) có',
  养: 'nuôi/dưỡng',
  内: 'bên trong/nội',
  円: 'viên/yên',
  再: 'lại/tái/nữa/sẽ',
  冏: 'sáng',
  冒: 'bốc lên/mạo',
  写: 'viết/tả/ghi',
  冢: 'mộ',
  冤: 'oan/oán',
  冰: 'băng/rét/đá',
  冲: 'xông/trùng/hướng/xung',
  决: 'quyết/vỡ',
  况: 'huống/huống hồ',
  冷: 'lạnh/lãnh',
  冻: 'đông lạnh/đông',
  净: 'chỉ toàn/sạch',
  准: 'chuẩn/đúng/chính xác/cho phép',
  凉: 'lạnh/mát',
  凑: 'góp/đụng/tập hợp/gom góp/thấu/họp/tiếp cận',
  凛: 'lẫm/run sợ',
  几: 'mấy/hầu như/vài',
  凳: 'băng ghế/đắng/ghế',
  凶: 'hung/ác/hung ác',
  凸: 'lồi',
  凹: 'lõm/ao',
  出: 'ra/xuất',
  函: 'văn kiện/hàm',
  凿: 'đục',
  刁: 'kén ăn/xảo quyệt',
  刃: 'lưỡi đao/nhận',
  分: 'phân/điểm/phần/phút',
  切: 'cắt',
  刊: 'san',
  划: 'vạch/hoạch/vẽ/hoa/họa',
  列: 'liệt/nhóm/đoàn/hàng',
  则: 'thì/tắc thì/tắc/lại/là/bản',
  刚: 'vừa/cương/mới vừa/cứng/cương',
  创: 'sáng tạo/sáng lập/chế/thương',
  初: 'sơ/ban đầu',
  删: 'xóa/xóa',
  判: 'phán/xử',
  刨: 'đào/(đào) bào',
  利: 'lợi/sắc',
  别: 'đừng/khác/chia ly/biệt/chớ/giắt',
  刮: 'cạo/phá/quát',
  到: 'đến/đáo/được',
  刷: 'xoát/cà/xoạt',
  刺: 'đâm/gai/thứ/thích',
  剁: 'chặt/băm',
  剃: 'cạo',
  削: 'gọt',
  剌: 'ngượng nghịu',
  前: 'trước/tiền',
  剐: 'róc thịt/quả',
  剔: 'loại bỏ/cạo',
  剖: 'mổ/phẫu',
  剜: 'khoét',
  剥: 'lột/bóc/tróc/bóc lột/bác',
  剧: 'kịch/phim',
  剩: 'thừa/thặng/thừa lại/còn dư lại/còn lại',
  剪: 'cắt/kéo/cắt bỏ',
  副: 'phó/thứ/bộ',
  剰: 'thừa',
  割: 'cắt/cát',
  剿: 'diệt/tiêu diệt',
  劈: 'bổ/phách/chẻ/chém',
  劝: 'khuyên/khuyến/khích lệ',
  办: 'xử lý/làm/bạn/đủ',
  功: 'công/công lao',
  劣: 'kém',
  助: 'trợ/giúp',
  劫: 'cướp/kiếp',
  劲: 'kình/sức lực',
  劳: 'cực khổ/lao',
  劵: 'khoán',
  势: 'thế/xu thế',
  勃: 'đột nhiên',
  勉: 'miễn/nỗ lực',
  勋: 'huân/công lao',
  勒: 'siết/lặc/cương/đè nén/ghìm cương',
  募: 'quyên/mộ',
  勤: 'cần/chuyên cần',
  勺: 'muôi/chước/muỗng',
  勿: 'chớ/vật',
  匀: 'vân/đều đặn',
  包: 'bao/túi',
  匐: 'bò xổm',
  匕: 'dao găm/chủy',
  化: 'hóa/tan',
  匙: 'chìa/thìa',
  匝: 'vòng/táp',
  匡: 'cứu/khuông',
  匪: 'phỉ',
  匹: 'thớt/thất',
  医: 'y/chữa',
  十: 'mười/thập/mươi/chục',
  千: 'ngàn/thiên/nghìn/ngàn',
  升: 'thăng/lên chức',
  午: 'trưa/buổi trưa/Ngọ',
  半: 'nửa/bán/rưỡi',
  卑: 'ti/thấp hèn',
  卒: 'tốt/chết',
  单: 'đơn/đan',
  卖: 'bán/mại',
  南: 'nam/Minami',
  卜: 'bốc/bói',
  占: 'chiếm/chiêm',
  卡: 'thẻ/kẹt/tạp/phiếu',
  卤: 'kho/lỗ',
  卦: 'quẻ',
  卧: 'nằm/ngọa',
  卫: 'vệ/Vệ',
  印: 'ấn/in',
  即: 'tức/là',
  却: 'lại/nhưng',
  卵: 'trứng/noãn',
  卷: 'quyển/cuốn/quăn',
  卸: 'gỡ/đẩy/cởi/tá/tháo',
  厂: 'nhà máy/hán/xưởng/cửa hàng',
  厉: 'lệ/nghiêm khắc',
  压: 'ép/áp/đè',
  厌: 'ghét/chán ghét/yếm',
  厕: 'xí/vệ sinh',
  厚: 'dày/hậu/dầy',
  厢: 'toa/mái hiên',
  去: 'đi/khứ',
  县: 'huyện/nếu là địa danh Nhật thì là tỉnh',
  叁: 'tam/ba',
  叆: 'ái/mờ mịt',
  又: 'lại/hựu/vừa',
  叉: 'xiên',
  及: 'cùng/và/cập/kịp/tới',
  友: 'bạn/hữu',
  反: 'phản/ngược',
  发: 'phát/tóc/',
  取: 'lấy/thủ',
  受: 'thụ/chịu/bị/được',
  变: 'biến/thay đổi',
  叙: 'tự/nói',
  叛: 'phản/phản bội',
  叠: 'chồng/xếp',
  口: 'miệng/ngụm/khẩu/thanh',
  句: 'câu/cú',
  另: 'khác/lánh',
  叨: 'lẩm bẩm/nhận',
  叩: 'gõ/khấu',
  只: 'chỉ/con/cái/chích',
  叫: 'gọi/để/bảo/làm/khiếu/kêu',
  召: 'triệu/cho đòi',
  叮: 'đinh/đốt/keng',
  可: 'nhưng/có thể/cũng/khả/đáng/thể',
  台: 'đài/thai/bàn',
  叱: 'quát',
  右: 'phải/bên phải',
  叶: 'lá/diệp',
  号: 'hào/số/hiệu/kêu/số hiệu/gào',
  司: 'ti/tư/ty',
  叼: 'điêu/tha/ngậm/ngậm trong mồm',
  叽: 'chít/kít/chít chít/chít chít (zhitsss)',
  吁: 'ô/thở dài',
  吃: 'ăn/cật/đồ ăn',
  各: 'các/tất cả/đều/mỗi/mỗi người',
  吆: 'yêu/hét',
  吊: 'xâu/treo/câu',
  吋: 'tấc',
  同: 'cùng/đồng',
  名: 'tên/danh',
  后: 'sau/hậu/sau khi/phía sau',
  吐: 'nôn/nhả/thổ/ói',
  向: 'hướng/hướng về phía/hướng về/xưa đến nay',
  吒: 'tra',
  吓: 'dọa/hách/hù dọa/sợ/doạ',
  吕: 'Lữ',
  吗: 'sao/ư/mạ/không/chưa/à',
  君: 'quân/-kun',
  吝: 'keo kiệt',
  吞: 'nuốt',
  吠: 'sủa/phệ',
  否: 'không/hay không/phủ/phủ định',
  吧: 'đi/a/ba/sao/không/chứ/nữa',
  吨: 'tấn/đốn',
  含: 'ngậm/nén/chứa/hàm',
  听: 'nghe/thính',
  吭: 'lên tiếng/cổ họng',
  吮: 'mút',
  吱: 'kít',
  吲: 'oành',
  吵: 'ầm ĩ/nhao nhao/sảo/ồn ào',
  吸: 'hút/hấp/hít',
  吹: 'thổi/xuy',
  吻: 'hôn/vẫn/mép/môi',
  吼: 'rống',
  吾: 'ngô/ta',
  呀: 'nha/à/ạ',
  呃: 'ách/ạch',
  呆: 'ngốc/nán lại/ở',
  呈: 'hiện/hiện lên/trình',
  告: 'cáo/kiện/nói với',
  呎: 'thước',
  呐: 'a/nột/...(nột-nói chậm!!!)',
  呔: 'này/oanh',
  呕: 'ọe/nôn/mữa',
  呖: 'kíu/lịch',
  呗: 'thôi/quá',
  员: 'viên/đủ/thành viên',
  呛: 'sặc/sang/hắc',
  呢: 'đâu/đây/đây này/ni/mà/mất/chứ',
  呤: 'lánh/đinh',
  呦: 'u/ôi',
  周: 'tuần/chu/xung quanh/vòng',
  呷: 'uống',
  命: 'mệnh/mạng/lệnh/mệnh lệnh',
  咀: 'nhai',
  咂: 'chép miệng',
  咄: 'đốt/ô hay',
  咋: 'thế nào/động/người/sao',
  和: 'cùng/và/hòa/như',
  咎: 'tội trạng',
  咐: 'phó',
  咒: 'chú/rủa/nguyền rủa',
  咔: 'két',
  咕: 'cô/cục cục',
  咖: 'cà/già',
  咝: 'ti/ư',
  咣: 'cạch',
  咧: 'liệt/rồi/nhếch',
  咩: 'be/be be',
  咪: 'meo/mễ',
  咬: 'cắn/giảo',
  咭: 'cười',
  咯: 'lạc/rồi/roài',
  咱: 'ta',
  咳: 'khục/khái/khụ/ho khan/khặc',
  咴: 'hí',
  咵: 'khoa trương',
  咸: 'mặn',
  咻: 'hưu/XÍU...UU!/xèo',
  咽: 'nuốt',
  哀: 'ai/buồn bã',
  品: 'phẩm/phẩm (品)',
  哂: 'mỉm cười/cười',
  哄: 'hống/dỗ/lừa/dỗ dành',
  哆: 'run',
  哈: 'a/cáp/hắc/ha',
  哉: 'ư/quá thay',
  响: 'vang/tiếng nổ/hưởng/vang dội',
  哑: 'câm/ách/khàn',
  哒: 'đát/đi',
  哗: 'hoa/xôn xao/ồn ào/rào',
  哚: 'đoá/ pặc/pặc',
  哞: 'mu/bò....ò.../tiếng bò rống/ò/Ùm...ụm bò....ò...tiếng bò rống',
  哟: 'nha/ơ',
  哢: 'lộng/kêu',
  哦: 'a/nga/ah/nha',
  哧: 'xoẹt/xoạt',
  哨: 'trạm canh gác/còi',
  哩: 'đấy/lý/dặm',
  哪: 'cái kia/cái nào/đâu/na/chưa/kia/đó/chỗ nào/nào',
  哭: 'khóc/khốc',
  哮: 'gào/hao',
  哺: 'mớm',
  哼: 'hừ/hanh/a',
  唆: 'toa/xui khiến',
  唇: 'môi/thần',
  唉: 'ai/ôi',
  唐: 'Đường/nhà Đường/đường',
  唔: 'ngô/A.../đừng/a',
  唠: 'lảm nhảm/lao',
  唤: 'gọi/hoán/kêu',
  唬: 'hù/hù dọa/doạ',
  售: 'bán',
  唱: 'hát',
  唳: 'lệ/Lê-eeee-eezz~!',
  唷: 'hừm',
  唾: 'nhổ/thóa',
  唿: 'hô',
  啃: 'gặm/khẳng',
  啄: 'mổ',
  啊: 'a/hả/ah',
  啐: 'xì/phun',
  啖: 'đạm/ăn',
  啜: 'xuyết/uống',
  啤: 'bia',
  啦: 'rồi/nữa/lạp/rồi',
  啪: 'ba/BA~/đùng',
  啮: 'gặm/gặm',
  啰: 'lải nhải',
  啸: 'khiếu/rít gào',
  啻: 'chỉ',
  啼: 'gáy',
  啾: 'thu/chụt',
  喀: 'rắc',
  喂: 'uy/cho ăn/này/đút',
  喃: 'lẩm bẩm',
  善: 'thiện/tốt',
  喇: 'còi/lạt',
  喈: 'dê',
  喉: 'hầu/cổ họng',
  喊: 'hô/hảm/quát/gọi/kêu',
  喏: 'ầy/dạ/ừ',
  喔: 'ờ',
  喘: 'thở/thở gấp',
  喙: 'mỏ',
  喜: 'vui/mừng/thích/hỉ',
  喝: 'uống/quát/hây',
  喧: 'huyên/tiếng động lớn',
  喰: 'xan/Ghoul',
  喵: 'meo/meo ô/meo meo/Meow/miêu',
  喷: 'phun',
  喻: 'dụ/ví',
  喽: 'đi/rồi',
  嗅: 'ngửi',
  嗑: 'gặm',
  嗒: 'cạch',
  嗓: 'tiếng nói',
  嗔: 'giận',
  嗖: 'sưu/vèo/vù',
  嗙: 'khoác lác/khoe khoang',
  嗜: 'thích/thị',
  嗝: 'nấc',
  嗡: 'ông/vù vù/vù',
  嗤: 'xùy/xuy/cười/giễu cợt/cười khúc khích/Xùy~~/xì',
  嗥: 'gào/grraaào',
  嗦: 'lắm điều',
  嗨: 'này/hải/high',
  嗯: 'ân/ừ/ừm/ân/dạ',
  嗲: 'ỏn ẻn/điệu',
  嗵: 'oành',
  嗷: 'ngao/NGAO/gào',
  嘀: 'đích/nói thầm/thầm thì/nghi ngờ/nghi hoặc',
  嘁: 'hứ',
  嘈: 'rầm rĩ/ồn ào',
  嘌: 'nhanh chóng',
  嘎: 'dát/Ự...c',
  嘘: 'xuỵt/hư',
  嘛: 'mà/ma/thôi/đây/đi/được/nha/sao',
  嘟: 'bĩu/tít/bĩu môi/bíp',
  嘡: 'boong boong',
  嘬: 'mút/toát',
  嘭: 'bành/thình thịch/oành',
  嘱: 'chúc/dặn bảo',
  嘲: 'trào/giễu cợt',
  嘴: 'miệng/chủy',
  嘶: 'tê/hí/híz-khà-zzz',
  嘻: 'ha ha/hi/ôi/hì hì/ha hả',
  嘿: 'hắc/này',
  噌: 'vụt',
  噎: 'nghẹn/ế',
  噔: 'đăng/thịch',
  噗: 'phốc/hơi thở phù/hút bập bập/hút từng hơn ngắn',
  噘: 'quyết/cong',
  噙: 'chứa',
  噜: 'lỗ/vò/líu ríu/nói nhiều',
  噢: 'úc/oh/ừ',
  器: 'khí/ (cụ)',
  噩: 'ác mộng/ngạc',
  噪: 'táo/kêu',
  嚎: 'gào/gào thét',
  嚏: 'hắt xì/hắt hơi/đế',
  嚓: 'xoạt',
  嚣: 'rầm rĩ/ồn ào',
  嚥: 'nuốt',
  嚯: 'hoắc/ồ',
  嚷: 'trách móc/nhượng/cho/kêu gào',
  嚼: 'nhai',
  囊: 'túi',
  囔: 'thì thầm',
  四: 'bốn/tứ',
  回: 'về/hồi/quay về/lần/trả lời',
  因: 'bởi vì/nhân/nguyên nhân/dựa vào',
  团: 'đoàn/vo',
  囧: 'quýnh/quýnh :-( 囧',
  园: 'vườn/viên',
  困: 'khốn/buồn ngủ/khốn/vây/vây khốn',
  围: 'vây',
  国: 'nước/quốc',
  图: 'đồ/hình/cầu',
  囿: 'câu nệ/hữu',
  圆: 'tròn',
  圈: 'vòng/quyển/giới',
  圏: 'vòng',
  土: 'thổ/đất',
  在: 'tại/đang/ở/再/lại',
  圮: 'tổn thương',
  场: 'trận/tràng/trường/cuộc/cơn/đợt/màn',
  均: 'đồng đều/quân/cùng/đều/đều',
  坏: 'xấu/hỏng/hư/phôi/phá hư',
  坐: 'ngồi/tọa',
  坑: 'hố/lừa/hãm hại/cái hố/lừa bịp/vũng hố',
  坛: 'đàn/vò',
  坟: 'mộ phần/phần/phần mộ',
  坠: 'rơi',
  坡: 'sườn núi',
  坦: 'thản/tank',
  坨: 'đống',
  坪: 'bãi/bình/bình địa',
  坯: 'phôi',
  坳: 'thung lũng',
  垂: 'rủ xuống/thùy/buông xuống',
  垃: 'rác',
  型: 'hình',
  垌: 'lan/động',
  垛: 'đống/gò',
  垠: 'ngần',
  垫: 'đệm/kê lót/lót',
  垭: 'khe núi',
  垮: 'đổ/suy sụp/sụp đổ',
  埃: 'ai/cát bụi/bụi',
  埋: 'chôn/mai/vùi',
  埵: 'đất cứng',
  基: 'cơ/dựa vào',
  堆: 'chồng/đống/chồng chất/đôi/đắp',
  堑: 'hố/hào',
  堕: 'đọa/rơi rụng',
  堡: 'bảo/lâu đài',
  堪: 'có thể',
  堵: 'chắn/chận',
  塌: 'sập/lõm xuống/sụp/giường/榻~',
  塑: 'tố/nặn',
  塘: 'đường/hồ',
  塞: 'nhét/nút/bỏ vào',
  填: 'lấp/điền',
  墨: 'mực/mặc',
  壁: 'bích/vách tường',
  壆: 'huyệt',
  壑: 'khe',
  壮: 'tráng/cường tráng',
  声: 'âm thanh/thanh/tiếng',
  壶: 'ấm/hồ/hũ',
  处: 'chỗ/nơi/xử',
  备: 'chuẩn bị/bị',
  夏: 'hạ/Hạ',
  外: 'bên ngoài/ngoại/ra/ở ngoài',
  多: 'nhiều/thêm/cỡ nào/đa',
  夜: 'đêm/dạ',
  够: 'đủ/với/cú',
  夥: 'hỏa/khỏa',
  大: 'lớn/đại',
  天: 'trời/ngày/thiên/bầu trời',
  太: 'quá/thái/rất',
  夭: 'thiên/yểu/天/yêu',
  央: 'ương/van xin/trung tâm',
  失: 'mất/thất',
  夸: 'khen/khoa trương/khoa/khoe',
  夹: 'kẹp/giáp/chen lẫn/gắp',
  奉: 'phụng/dâng tặng',
  契: 'khế/văn tự',
  奔: 'chạy/bôn',
  奖: 'thưởng/tưởng/khen',
  套: 'bộ/đeo/vỏ/bộ đồ/buộc',
  奢: 'xa xỉ',
  奶: 'sữa/nãi',
  她: 'nàng/mụ/nàng/他',
  好: 'tốt/hảo/được/thật/dễ/thích/xong',
  妈: 'mẹ/mụ',
  妊: 'nhẫm',
  妒: 'ghen',
  妓: 'kỹ/kỹ (nữ)',
  妙: 'diệu/hay',
  妞: 'cô nàng/nàng/con gái/nữu',
  妨: 'trở ngại/phương',
  妳: 'ngươi/nàng',
  妻: 'vợ/thê',
  始: 'bắt đầu/thủy/mới',
  姓: 'họ/tính',
  姜: 'gừng/khương',
  姣: 'giảo/tướng mạo',
  姥: 'bà ngoại',
  姬: 'cơ/hime',
  姿: 'tư/tư thế/dáng dấp',
  娃: 'bé con/em bé/oa/trẻ con',
  娘: 'nương/mẹ/mẹ',
  娟: 'quyên/đẹp đẽ/đẹp',
  娶: 'cưới/lấy/thú/lấy',
  娼: 'kỹ nữ',
  婚: 'cưới/hôn',
  婧: 'tịnh/nhu',
  婿: 'tế/con rể',
  媒: 'môi/mai',
  媵: 'thiếp',
  嫁: 'gả/giá',
  嫉: 'đố kị/tật',
  嫌: 'ngại',
  嫖: 'chơi gái/chơi/phiêu/chơi trai',
  嫩: 'non',
  嬉: 'đùa/chơi',
  嬴: 'doanh/thắng/Doanh',
  子: 'tử/con',
  孔: 'lỗ/khổng',
  孕: 'mang thai/dựng/chửa',
  字: 'chữ/tự',
  孬: 'nhút nhát',
  孰: 'ai',
  孱: 'mềm yếu',
  孵: 'ấp trứng/ấp',
  孺: 'trẻ con/nhụ',
  宁: 'thà/ninh',
  它: 'nó/tha/khác',
  宅: 'trạch/chỗ ở',
  安: 'an/sao',
  完: 'xong/hết/hoàn',
  宏: 'hồng',
  定: 'định/bình tĩnh',
  宜: 'nghi/nên/thích hợp',
  实: 'thực/đầy',
  宠: 'sủng/cưng chiều',
  室: 'thất/phòng',
  宴: 'yến/tiệc rượu',
  容: 'cho/dung/sắc mặt',
  宽: 'rộng/khoan/chiều rộng',
  寄: 'gửi',
  富: 'giàu',
  寐: 'ngủ',
  寒: 'lạnh/hàn',
  寝: 'ngủ',
  察: 'xem xét/xét',
  寮: 'lều',
  寸: 'tấc/inch/thốn',
  对: 'đối/đúng/đối với/với/đôi',
  寺: 'chùa/tự',
  寻: 'tìm/tầm',
  射: 'bắn/xạ',
  将: 'đem/sẽ/tướng/tương/sắp',
  小: 'nhỏ/tiểu',
  少: 'thiếu/ít/trẻ',
  尔: 'ngươi/thôi',
  尖: 'nhọn/tiêm/the thé/nhạy bén/mũi',
  尘: 'bụi/trần',
  尚: 'còn/chú trọng/vẫn còn',
  尛: 'nhỏ bé',
  尝: 'nếm/từng/thường',
  尤: 'càng',
  尧: 'Nghiêu',
  尬: 'giới/ngượng',
  就: 'liền/thì/tựu/ắt/thành/chính',
  尴: 'lúng túng khó xử',
  尺: 'xích/thước',
  尽: 'tận/tẫn/tận',
  尾: 'đuôi/vĩ',
  尿: 'nước tiểu/đi tiểu',
  局: 'cục/(ván) cục',
  层: 'tầng/tằng',
  屄: 'bi/âm hộ/lồn',
  屋: 'phòng',
  屎: 'phân/cứt/thỉ',
  屏: 'bình phong/màn hình/hơi',
  屑: 'mảnh',
  展: 'triển/giương/发',
  屠: 'đồ/giết/tàn sát',
  屡: 'nhiều lần',
  履: 'giày/lý',
  屯: 'đồn',
  山: 'núi/sơn',
  岁: 'tuổi/tuế',
  岂: 'há/khởi/há lại',
  岗: 'cương vị/tốp',
  岣: 'cẩu/câu',
  岳: 'nhạc/ngọn núi',
  岸: 'bờ',
  峁: 'mão/Mão',
  峪: 'dụ',
  峬: 'xinh đẹp duyên dáng',
  峰: 'phong/ngọn núi/Phong',
  崎: 'kỳ/khi',
  崖: 'sườn núi/nhai',
  崛: 'vùng dậy/quật',
  崩: 'sập/băng/sụp đổ/vỡ',
  崽: 'con/tể',
  嵝: 'lũ/Lũ',
  嶓: 'Bá Trùng',
  巅: 'đỉnh',
  川: 'xuyên/sông',
  巢: 'tổ/sào/sào huyệt',
  左: 'trái/tả/bên trái',
  巧: 'xảo/khéo léo/đúng dịp',
  巨: 'cự/to/lớn',
  巫: 'Vu/vu',
  差: 'kém/chênh lệch/soa/sai/xui xẻo/sai dịch/error',
  己: 'mình/mấy',
  已: 'đã/thôi/dĩ',
  巴: 'ba/mong',
  巷: 'ngõ hẻm',
  巾: 'khăn',
  币: 'tệ/tiền',
  市: 'thành phố/thị/chợ/mua/thị trường',
  布: 'vải/bố',
  帅: 'soái/đẹp trai/ngầu',
  帆: 'buồm',
  帕: 'khăn/bọc',
  帘: 'màn/mảnh vải',
  帚: 'cây chổi',
  帛: 'lụa/tơ lụa',
  带: 'mang/đái/đeo/kéo/vùng/đai/lẫn',
  帧: 'tấm/tránh',
  席: 'tịch/bữa tiệc/ghế',
  帮: 'giúp/bang/đám/mép',
  帽: 'mũ/cái mũ',
  幅: 'bức/biên độ',
  幌: 'màn trướng',
  幔: 'màn/mạn',
  幕: 'màn',
  幡: 'cờ/lá cờ/phiên',
  干: 'làm/cạn/khô/kiền',
  平: 'bình/phẳng/hòa/mét vuông',
  年: 'năm/niên/tuổi',
  并: 'cũng/đồng thời/tịnh',
  幸: 'hạnh/may mắn',
  广: 'rộng/quảng/rộng rãi',
  庇: 'che chở/tí',
  床: 'giường/sàng',
  库: 'kho/khố',
  应: 'ứng/đáp/ứng với/nên',
  底: 'ngọn nguồn/đáy/thực chất/cùng/cuối',
  店: 'cửa hàng',
  座: 'tòa/tọa/ngồi/toà',
  庯: 'xinh đẹp',
  廉: 'liêm/Liêm',
  廊: 'hành lang',
  廋: 'lục soát/ẩn náu',
  延: 'diên/kéo dài',
  廷: 'đình/triều đình',
  建: 'xây/kiến',
  廿: 'hai mươi',
  开: 'mở/lái/khai/nở/sôi/nổ/chạy',
  异: 'dị/khác',
  弃: 'vứt bỏ',
  弄: 'làm/làm cho/kiếm/lộng/chuẩn bị/chơi',
  式: 'thức/Shiki',
  引: 'dẫn/rút/rời xa/thên',
  弗: 'không',
  张: 'trương/tờ/mở/giương',
  弦: 'dây cung/huyền',
  弧: 'cung/hình cung/cầu vòng',
  弩: 'nỏ',
  弯: 'cong/loan/chỗ ngoặt/khom/ngoặt (khom)',
  弱: 'yếu/nhược',
  弹: 'đạn/đánh/gảy/bắn/nảy',
  强: 'mạnh/cường/mạnh mẽ',
  弾: 'đạn/弹',
  归: 'về/thì/thuộc về/quy',
  当: 'khi/làm/coi là/đương/nên/đem/đáng/coi',
  录: 'lục/ghi chép/quay/sao chép',
  彩: 'màu/thương/thải',
  彬: 'bân/nho nhã',
  彰: 'rõ/chương',
  影: 'ảnh/Kage',
  彼: 'kia/đối phương',
  往: 'hướng/vãng/đã qua/đi/hướng về',
  征: 'chinh/trưng thu',
  径: 'đường/kính',
  待: 'đợi/đãi/chờ/ở',
  很: 'rất',
  後: 'sau/hậu',
  徒: 'đồ/uổng phí',
  得: 'đến/phải/được/đắc/bị/mắc',
  循: 'theo',
  微: 'hơi/vi',
  德: 'đức/Druid',
  必: 'tất/nhất định/tất nhiên',
  忆: 'ức/(ký) ức',
  忌: 'kị',
  忐: 'lo lắng',
  忑: 'lo lắng',
  忒: 'quá',
  忖: 'nghĩ kĩ',
  忘: 'quên',
  忙: 'bận bịu/vội vàng/bề bộn/mang',
  忝: 'thẹn',
  忤: 'ngang ngược',
  忧: 'lo',
  快: 'nhanh/khoái/mau/hơn/sắp',
  念: 'niệm/đọc',
  忻: 'hân/hãn',
  忽: 'chợt/hốt',
  怀: 'mang/hoài/ngực',
  态: 'thái/trạng thái',
  怂: 'sợ/kinh sợ/hèn/hãi',
  怎: 'sao/chẩm',
  怒: 'giận/nộ',
  怔: 'giật mình/sợ/sợ run',
  怕: 'sợ/phạ',
  怖: 'sợ',
  怜: 'yêu/thương',
  思: 'nghĩ/tưởng nhớ/tư',
  怠: 'lười biếng/đãi',
  急: 'gấp/cấp/cấp bách',
  怦: 'phanh/thịch',
  性: 'tính/tính chất',
  怩: 'ngượng nghịu/ny',
  怪: 'quái/trách/quá',
  怯: 'e sợ',
  怵: 'sợ hãi/sợ',
  怼: 'đỗi/oán/đánh/đập/chọc',
  恁: 'thế này',
  恂: 'tuân/Tuân',
  恃: 'ỷ lại/thị',
  恋: 'luyến/yêu',
  恍: 'bừng tỉnh/hoảng',
  恐: 'sợ/chỉ',
  恕: 'tha thứ/thứ cho',
  恙: 'việc gì/bệnh nhẹ/bệnh',
  恤: 'lo lắng/tuất/thương xót/T-shirt',
  恩: 'ân/dạ/ừ',
  恬: 'điềm/yên ổn',
  恭: 'cung/cung kính',
  息: 'hơi thở/tức',
  恰: 'vừa/đúng/vừa lúc',
  恶: 'ác/buồn nôn',
  恸: 'thảm thiết',
  恻: 'xót xa',
  恼: 'buồn bực/ảo não/não',
  悄: 'lặng lẽ',
  悌: 'đễ/kính',
  悍: 'hung hãn',
  悔: 'hối hận/会',
  悖: 'bội/ngược lại',
  悚: 'sợ',
  患: 'hoạn/mắc',
  悦: 'duyệt/vui mừng',
  您: 'ngài/nâm/người',
  悬: 'treo/huyền/nâng',
  悲: 'buồn/bi',
  悸: 'sợ',
  惋: 'thương tiếc',
  惑: 'nghi ngờ/hoặc',
  惕: 'kính sợ',
  惘: 'ngơ ngẩn',
  惜: 'tiếc',
  惦: 'nghĩ về/nhớ',
  惧: 'sợ',
  惩: 'trừng phạt/trừng',
  惬: 'thiếp',
  惭: 'tàm/tàm (thẹn)',
  惮: 'đan/sợ',
  惯: 'quen/thói quen/nuông chiều',
  惰: 'biếng nhác',
  想: 'nghĩ/muốn/nhớ/tưởng',
  惶: 'hoảng sợ',
  惹: 'gây/nhạ/làm cho/rước lấy/chọc',
  愁: 'sầu/buồn/ưu sầu',
  愈: 'càng/dũ/khỏi bệnh',
  愕: 'kinh ngạc/ngạc',
  感: 'cảm giác/cảm/cảm (giác)',
  愠: 'hờn/giận',
  愣: 'sững sờ/cứ thế/lỗ mãng',
  愧: 'thẹn/xấu hổ/quý',
  愿: 'nguyện/nguyện vọng',
  慌: 'hoảng/sợ',
  慢: 'chậm/mạn/nhờn',
  慰: 'an ủi',
  慵: 'thung/biếng nhác',
  慾: 'dục/muốn/ham',
  憋: 'nghẹn/nín',
  憨: 'khờ/đơn giản',
  憷: 'sợ hãi',
  憾: 'tiếc',
  懂: 'hiểu/đổng/u mê/bối rối',
  懈: 'trễ/lười',
  懒: 'lười/lại/lãn/làm biếng/mệt mỏi/kiệt sức',
  戈: 'qua/thương/mâu',
  戊: 'Mậu/mậu',
  戍: 'đóng giữ',
  戏: 'hí/hí kịch/kịch',
  成: 'thành',
  我: 'ta/ngã',
  戒: 'giới/cai',
  或: 'hoặc/có lẽ/có thể',
  截: 'đoạn/chặn/tiệt',
  戳: 'đâm/trạc/dãy',
  戴: 'mang',
  房: 'phòng',
  所: 'chỗ/sở/viện',
  扁: 'dẹp/làm thịt/bẹp/đánh',
  扇: 'phiến/quạt',
  手: 'tay/thủ',
  才: 'mới/tài',
  扎: 'đâm/buộc/mổ/trát/ghim',
  扑: 'nhào/phốc/bổ nhào',
  扒: 'đào/bới ra',
  打: 'đánh/đả',
  扔: 'ném/nhưng/vứt',
  托: 'nhờ/nắm/thác/nâng',
  扛: 'gánh/khiêng',
  扞: 'cản',
  扣: 'trừ/chụp/khấu trừ/cài',
  扩: 'khuếch trương',
  扫: 'quét',
  扬: 'giương/dương/vung/hất',
  扭: 'xoay/uốn éo/nữu/quay tay',
  扮: 'đóng vai/đóng/giả trang/phẫn/quấy/nhào đều',
  扯: 'kéo/xé/xả',
  扰: 'nhiễu/quấy nhiễu',
  扳: 'vịn/ban/vặn/lật',
  扶: 'đỡ/vịn/phù',
  批: 'nhóm/phê',
  扼: 'ách/chặn/bóp',
  找: 'tìm/hoa',
  承: 'nhận/thừa/thừa nhận',
  抄: 'chép/sao/vớ/xét',
  把: 'đem/thanh/bả/ván',
  抓: 'bắt/trảo/trảo/gãi/',
  投: 'ném/quăng/đầu',
  抖: 'run/đẩu/run rẩy/phấn chấn',
  折: 'gãy/xếp/chiết khấu/lộn/gấp',
  抚: 'phủ/an ủi',
  抛: 'ném/phao/vứt/quăng',
  抠: 'móc/gảy/keo kiệt',
  抡: 'vung mạnh/kén/chọn/xoay',
  抢: 'đoạt/thưởng/cướp',
  护: 'hộ/bảo hộ',
  披: 'khoác/khoác trên vai',
  抬: 'nhấc/khiêng/giơ lên/sĩ/đánh/mang',
  抱: 'ôm/bão',
  抵: 'chống đỡ',
  抹: 'bôi/xóa/mạt/vệt',
  抽: 'rút/quất/trừu/nảy/lấy ra/nhổ/đánh/hút',
  抿: 'nhấp/chải/mân',
  拂: 'phật',
  担: 'gánh',
  拆: 'phá/hủy đi/sách',
  拈: 'nhặt',
  拉: 'kéo/lạp/hướng',
  拌: 'trộn lẫn',
  拍: 'đập/đấu/quay/chụp/phách/đánh',
  拎: 'xách',
  拏: 'nã',
  拐: 'ngoặt/gậy/lừa gạt/quải/nạng',
  拓: 'thác/mở đất',
  拔: 'nhổ/bạt/rút/nhổ/rút ra',
  拖: 'kéo/tha',
  拗: 'cố chấp/ảo/bẻ/khó lay chuyển/đè nén đi/cưỡng',
  拙: 'vụng/kém cỏi',
  拚: 'vứt/biện',
  招: 'chiêu/nhận/làm/nhận tội',
  拜: 'bái/lạy/bye',
  拟: 'mô phỏng/nghĩ/nghĩ ra',
  拢: 'lũng/áp sát',
  拣: 'lấy/chọn/kiếm',
  拥: 'ủng/cầm giữ',
  拦: 'cản/ngăn đón/lan/ngăn',
  拧: 'vặn/nhéo/vắt/ninh',
  拨: 'phát/gẩy',
  择: 'chọn',
  拭: 'lau',
  拱: 'ủi/cúi lưng/nhú',
  拴: 'buộc',
  拼: 'liều/hợp lại/ghép',
  拽: 'túm/chảnh/túm',
  拾: 'nhặt/mười',
  拿: 'cầm/nã/nắm',
  持: 'cầm/trì/nắm',
  挂: 'treo/hack',
  指: 'chỉ/ngón tay',
  按: 'theo/theo như/án/vỗ/ấn/chứng cứ/theo : đè',
  挎: 'đeo/khoá',
  挑: 'chọn/chống/chọc/khều/thiêu/khiêu/gánh/hất',
  挖: 'đào/oạt/móc',
  挟: 'mang/hiệp/cầm/kẹp',
  挠: 'cào/gãi/quấy nhiễu/cong',
  挡: 'cản/ngăn cản/đáng/chặn',
  挣: 'kiếm/giãy/tranh/tránh/giãy (kiếm được)',
  挤: 'chen/lách vào',
  挥: 'vung',
  挨: 'chịu/lần lượt/ai/kề bên',
  挪: 'chuyển',
  挫: 'áp chế',
  挲: 'vuốt/sa',
  挺: 'rất/gắng/đĩnh/ủng hộ/cố gắng/khẩu/thẳng',
  挽: 'kéo/xắn/vãn',
  捂: 'che/ô/bưng bít',
  捅: 'đâm/chọc/thống/thọt',
  捆: 'trói/khổn/buộc/bó',
  捉: 'bắt/hái/tróc/nắm bắt',
  捋: 'vuốt/gỡ',
  捎: 'mang hộ',
  捏: 'bóp/nắm/niết/nặn',
  捕: 'bắt/bổ',
  捞: 'vớt/kiếm/lao/mò',
  损: 'tổn hại/cay độc',
  捡: 'nhặt/kiểm/kiếm',
  换: 'đổi/thay/hoán/đổi lại/đổi',
  捧: 'nâng/phủng/thổi phồng',
  据: 'theo/cư/cứ/căn cứ',
  捱: 'chống cự',
  捶: 'nện/chủy/đấm/nện',
  捷: 'nhanh/thắng',
  捻: 'vê',
  掀: 'vén/nhấc lên/nhấc',
  掂: 'ước lượng',
  授: 'thụ/dạy',
  掉: 'rơi/mất/bỏ/đi',
  掌: 'chưởng/bàn tay',
  掏: 'móc/đào/lấy ra',
  掐: 'bóp/véo/kháp/bấm',
  排: 'sắp xếp/hàng/bài/đứng hàng/trung đội',
  掘: 'đào/móc',
  掠: 'cướp/lướt',
  探: 'dò xét/tham/dò/thăm',
  掣: 'xiết',
  接: 'tiếp/nhận/nối',
  推: 'đẩy/thôi',
  掩: 'che đậy/ dấu/yểm/che/đậy/dấu',
  措: 'xử chí',
  掰: 'tách ra',
  掳: 'bắt/cướp',
  掴: 'tát',
  掷: 'ném/trịch/quăng',
  掸: 'phủi',
  掺: 'trộn lẫn/sảm',
  掼: 'quăng/quán',
  揉: 'vò/văn vê/nhu/thuận/vân vê/nhào nặn',
  揍: 'đánh/tấu',
  描: 'tô lại/copy',
  提: 'xách/nói/lấy/nâng/đề/dẫn/nhắc đến',
  插: 'cắm/chọc vào/sáp/xuyên vào/trồng/cấy/xuyên',
  揖: 'vái chào/ấp',
  握: 'nắm/ác/cầm',
  揣: 'thăm dò/ước lượng/sủy/đo',
  揩: 'lau',
  揪: 'nắm chặt/tóm/nhéo',
  揭: 'bóc/vạch trần',
  援: 'viện binh',
  揽: 'ôm/ôm đồm',
  搀: 'nâng',
  搁: 'đặt',
  搂: 'ôm/lâu/vơ/quơ/kéo',
  搅: 'quấy/khuấy',
  搏: 'đọ sức/đập/bác',
  搓: 'xoa/chà xát',
  搔: 'gãi',
  搜: 'lục soát/sưu',
  搞: 'làm/kiếm/trị/cảo/làm cho',
  搡: 'đẩy/táng',
  搬: 'chuyển/đem/bàn/dọn sạch/mang/dời',
  搭: 'dựng/đáp/đi',
  携: 'mang theo/dắt',
  搽: 'bôi',
  摁: 'nhấn',
  摄: 'nhiếp/chụp',
  摆: 'bày/bãi/mở',
  摇: 'dao/dao động/rung/lắc',
  摊: 'bày/quán/than/vuốt/chia đều',
  摒: 'bài trừ gạt bỏ',
  摔: 'quẳng/ngã/suất/đánh ngã/té',
  摘: 'hái/trích',
  摞: 'chồng/chồng chất',
  摧: 'phá vỡ/tồi',
  摸: 'sờ/mò/mạc/tìm tòi',
  摺: 'gấp/bẻ',
  撂: 'đặt xuống',
  撅: 'vểnh lên',
  撑: 'chống đỡ/căng cứng/xanh/no/đủ/chống',
  撒: 'vung/tát/tản/tung ra/xòe ra/xức/làm càn',
  撕: 'xé/tê/nhắc/kéo',
  撞: 'đụng/chàng/khua/va',
  撤: 'rút/rút lui/triệt',
  撩: 'vẩy/trêu chọc',
  撬: 'nạy ra/khiêu',
  撮: 'túm/dúm',
  撵: 'đuổi/niện/đuổi đi',
  撷: 'hiệt/ngắt lấy',
  撸: 'lột/tuốt/cách chức/triệt/vén',
  撼: 'lay',
  擀: 'lau kỹ/giã/cán',
  擅: 'thiện/tự ý',
  操: 'thao/sử dụng',
  擎: 'giơ cao',
  擒: 'cầm/bắt/tóm',
  擘: 'phách/ngón cái',
  擡: 'nâng/đài',
  擤: 'lau',
  擦: 'xát/lau/xoa/sát/cọ xát lấy',
  攀: 'trèo/víu/phàn',
  攒: 'tích lũy/tích góp',
  攘: 'cướp/bài trừ',
  攥: 'nắm',
  攫: 'quắp/chiếm',
  支: 'chi/thứ/nhánh/giữ/cầm',
  收: 'thu/nhận/bắt',
  改: 'đổi/sửa',
  放: 'thả/phóng/để/đuổi/bỏ/chiếu',
  故: 'cho nên/cố/nguyên nhân',
  教: 'giáo/dạy/để/bị',
  敞: 'mở',
  敢: 'dám/cảm/tiến lên/bạo dạn/có dũng khí',
  敦: 'thật thà',
  数: 'số/đếm/mấy/sổ/trách mắng/kể/cân nhắc/tỉnh phỏng/luôn luôn/kể ra',
  敲: 'gõ/xao/đập',
  整: 'cả/chỉnh/đều/sửa sang/làm',
  敷: 'thoa',
  文: 'văn/đồng',
  斋: 'trai/chay',
  斑: 'ban/lốm đốm/Madara',
  料: 'liệu/liều',
  斜: 'nghiêng/tà/vẹo',
  斥: 'khiển trách/chê/khai thác/xích/đuổi/bác/dò',
  斧: 'búa',
  斩: 'trảm/chém',
  断: 'đoạn/nhất định/gãy/đánh gãy/cắt',
  新: 'mới/tân',
  方: 'phương/mới/vuông',
  於: 'với/sinh/于',
  旁: 'bên cạnh/bàng/cạnh/bên',
  旅: 'lữ/hành trình',
  旋: 'xoáy',
  旗: 'cờ/flag/kỳ',
  无: 'không/vô',
  既: 'đã/vừa/ký/rồi/tức/thì là',
  日: 'ngày/nhật/mặt trời/xxx',
  旦: 'sáng',
  旧: 'cũ/cựu',
  早: 'sớm/tảo',
  旯: 'xó',
  时: 'lúc/thì/khi/giờ/thời',
  旷: 'bỏ/khoáng',
  昀: 'quân/vân',
  昌: 'xương/hưng thịnh/hưng',
  明: 'minh/sáng',
  昏: 'bất tỉnh/hôn/ngất',
  易: 'dễ/dịch/dễ dàng/đổi',
  昔: 'tích/xưa kia',
  昙: 'đàm/đám mây dày',
  星: 'tinh/sao',
  映: 'chiếu/ánh',
  昨: 'hôm qua',
  是: 'là/thị/đúng/vâng/phải',
  昴: 'mão/Subaru',
  昵: 'mật',
  昼: 'ban ngày',
  显: 'hiển/lộ ra/lộ vẻ/hiện ra',
  晁: 'Triều/triều',
  晃: 'lắc/hoảng/lay động/sáng ngời',
  晋: 'tấn/tiến lên/Tấn',
  晒: 'phơi/phơi nắng',
  晕: 'choáng/chóng mặt/vựng/vầng sáng/ngất/choáng váng',
  晚: 'muộn/chiều muộn/tối',
  晡: 'giờ Thân',
  晨: 'thần/sáng sớm',
  晰: 'tích/rõ ràng',
  晳: 'tích',
  晴: 'tình/trời trong xanh',
  晾: 'phơi/gạt/bỏ',
  暇: 'rảnh',
  暍: 'cảm nắng',
  暑: 'nóng',
  暖: 'ấm/noãn/ấm áp',
  暧: 'ái/mờ/tối',
  暮: 'mộ/chiều',
  曜: 'diệu/ánh sáng',
  曰: 'nói/viết/gọi',
  曳: 'dắt',
  更: 'càng/canh/đổi/lại thêm/hơn',
  曼: 'man/mạn',
  曾: 'từng/tằng/bèn',
  替: 'thay',
  最: 'nhất/tối/rất',
  月: 'nguyệt/tháng/trăng',
  有: 'có/hữu',
  朋: 'bằng/bằng hữu',
  服: 'phục/dùng/mặc/uống',
  望: 'nhìn/ngắm/vọng/trông chờ/nhìn qua',
  朝: 'hướng/sớm mai/sớm/triều',
  木: 'mộc/gỗ/cây',
  未: 'chưa/vị/Mùi',
  末: 'mạt/mọn/không/hết/cuối/mỏng/nhẹ/hẹp/chưa',
  本: 'vốn/bản',
  朱: 'Chu/chu/đỏ thắm',
  机: 'cơ/máy bay/máy',
  杀: 'giết/sát',
  杂: 'tạp/hỗn tạp/lẫn lộn',
  杆: 'cán/cái',
  杈: 'chạc/xoa',
  束: 'buộc/bó/chùm',
  杠: 'đòn khiêng/gạch',
  条: 'đầu',
  来: 'đến/tới/lai',
  杳: 'xa ngút ngàn dặm',
  杵: 'xử/đứng',
  松: 'lỏng/tùng',
  板: 'tấm/bản/cửa',
  极: 'cực/vô cùng',
  枕: 'gối',
  林: 'lâm/rừng',
  枚: 'mai/miếng/viên',
  枝: 'nhánh/cành',
  枢: 'trụ cột/khu',
  枣: 'táo/tảo/cây táo',
  枪: 'thương/súng/phát đạn/đạn',
  枫: 'phong/cây phong',
  架: 'đỡ/khung/cái/chiếc/giá/đánh/trận',
  枷: 'gông/cái gông',
  柄: 'chuôi/thanh',
  染: 'nhiễm/nhuộm',
  柙: 'cũi/hiệp',
  柜: 'tủ',
  柠: 'nắm',
  柩: 'quan tài',
  柴: 'củi/sài',
  柽: 'sinh',
  栅: 'rào/hàng rào',
  标: 'tiêu/đánh dấu/ngọn/nhãn hiệu',
  栋: 'tòa/tòa nhà/đống/nóc',
  栏: 'cột/thanh/lan',
  树: 'cây/thụ/dựng',
  栓: 'chốt/cái chốt',
  栖: 'dừng/tê',
  校: 'trường học/hiệu/giáo',
  株: 'gốc/gốc cây',
  格: 'cách/nghiên cứu/ô vuông/ô',
  栽: 'cắm/trồng',
  桀: 'kiệt/khặc',
  桅: 'cột buồm',
  框: 'khung',
  桌: 'bàn/trác',
  桑: 'tang/cây dâu',
  桖: 'mộc huyết',
  桢: 'trinh',
  档: 'ngăn/hồ sơ/đương/cấp/bậc',
  桥: 'cầu/kiều',
  桨: 'mái chèo',
  桩: 'cọc/cái cọc',
  桲: 'dụng cụ đập lúa',
  桶: 'thùng/dũng',
  桿: 'que',
  梁: 'lương/xà nhà/dầm',
  梆: 'bang/mõ',
  梏: 'cùm',
  梓: 'tử/Azusa',
  梢: 'sao/ngọn',
  梭: 'toa/con thoi',
  梯: 'bậc thang/thê/cái thang/trèo',
  梳: 'chải/chải đầu/sơ',
  棉: 'bông vải/bông',
  棋: 'cờ/quân cờ',
  棕: 'tông/nâu',
  棚: 'lều/rạp',
  森: 'sâm/dày đặc',
  棱: 'lăng/đỏ quạch (tỏ ý chán ghét)/cạnh',
  棵: 'khỏa/cây/gốc cây',
  棺: 'quan tài/hòm quan tài',
  椅: 'ghế dựa/ghế/ghế tựa',
  椎: 'chùy',
  椒: 'tiêu/ớt',
  楼: 'lâu/lầu',
  榨: 'ép',
  榻: 'giường/giường',
  槁: 'khô héo',
  槊: 'sóc/giáo',
  槲: 'sồi',
  槽: 'rãnh/cái rãnh',
  槿: 'cẩn/cẩn (hoa dâm bụt)',
  樟: 'cây nhãn',
  模: 'mô hình/khuông/mô hình (khuôn đúc)',
  樤: 'đầu',
  橐: 'bễ thổi lửa',
  橘: 'quýt/quất',
  橙: 'cam/quả cam/chanh/ghế',
  橛: 'cọc/quyết',
  橡: 'cao su',
  橹: 'mái chèo/lỗ/thuẫn',
  檐: 'mái hiên nhà',
  檠: 'kềnh/kình',
  檩: 'đòn tay',
  欂: 'đấu cùng',
  欠: 'thiếu/thiếu nợ/khiếm/ngáp/nợ',
  次: 'lần/thứ',
  欢: 'hoan/vui mừng',
  欣: 'hân/vui mừng',
  欲: 'muốn/dục',
  欺: 'lấn/ức hiếp/bắt nạt',
  款: 'khoản/kiểu',
  歇: 'nghỉ',
  歉: 'xin lỗi',
  止: 'dừng/dừng lại',
  正: 'chính/đang/dương/thẳng',
  此: 'này/thử/ấy/bèn/đây',
  步: 'bước/bộ',
  武: 'võ/vũ',
  歪: 'lệch nghiêng',
  歹: 'xấu/ác quỷ',
  死: 'chết/tử',
  歼: 'diệt',
  殂: 'chết',
  殃: 'ương/hại',
  殇: 'thương/chết non',
  殊: 'thù/khác biệt/đặc biệt',
  毅: 'nghị/kiên quyết',
  每: 'mỗi/thường/từng/mỗi khi/mỗi lần',
  比: 'so/bỉ/so với',
  毗: 'tì',
  毙: 'đánh chết/giết',
  毛: 'lông/mao/cọng lông',
  毫: 'hào/chút nào',
  毯: 'thảm/tấm thảm',
  氅: 'áo  khoác/áo cừu/áo khoác',
  气: 'khí/chọc tức/tức giận/tức/giận',
  氢: 'hydro',
  氦: 'heli',
  氧: 'dưỡng/oxi',
  氮: 'nitơ/nitrogen',
  水: 'nước/thủy',
  永: 'vĩnh/vĩnh viễn/lâu dài',
  氾: 'giàn giụa',
  汀: 'đinh/bãi bồi',
  汁: 'nước/nhựa',
  求: 'cầu/tìm/trách/xin/ngang/van',
  汇: 'chuyển/hợp thành/',
  汐: 'tịch/Tịch',
  汗: 'mồ hôi/hãn/đổ mồ hôi',
  汝: 'nhữ/mày',
  汞: 'thủy ngân',
  江: 'sông/giang',
  池: 'hồ/ao/trì',
  汤: 'canh/thang/súp',
  汪: 'uông/gâu',
  汰: 'bỏ/thái',
  汶: 'vấn/Vấn',
  汽: 'hơi/khí',
  沆: 'hàng',
  沈: 'thẩm/trầm',
  沉: 'chìm/nặng/trầm/lặn',
  沏: 'pha/ngâm vào nước',
  沓: 'xấp/xấp (liên tục)',
  沖: 'trùng/vọt',
  沙: 'cát/sa',
  沛: 'bái',
  沟: 'câu/kênh mương/rãnh mương',
  没: 'không có/ngập/chìm/chưa/mất',
  沤: 'ngâm ủ',
  沫: 'mạt/bọt',
  河: 'sông/hà',
  沷: 'tẩy rửa sạch sẽ',
  沸: 'sôi',
  油: 'dầu/du/mỡ',
  治: 'trị/quản lý',
  沾: 'dính',
  沿: 'xuôi theo/duyên/ven/bờ/mép/dọc theo',
  泉: 'suối/tuyền/Izumi',
  泊: 'đỗ',
  泓: 'hoằng/dòng',
  泛: 'hiện/hiện lên/hiện ra',
  泡: 'ngâm/cua/phao/bọt/pha/ngâm nước',
  波: 'sóng/đợt/làn/ba/',
  泣: 'khóc',
  泥: 'bùn/nê',
  注: 'chú/rót',
  泪: 'nước mắt',
  泫: 'huyền',
  泳: 'lặn',
  泵: 'bơm/cô/tuyền',
  泻: 'tả/cuồn cuộn/chảy nước',
  泼: 'giội',
  洐: 'hành/diễn',
  洒: 'vẩy/rơi vãi/sái/tẩy/chót vót/tung',
  洗: 'tẩy/tắm/rửa/giặt rửa/giặt',
  洛: 'Lạc',
  洞: 'động/lỗ',
  活: 'sống/công việc/hoạt',
  流: 'lưu/chảy',
  浅: 'cạn/nhạt/nông/thiển',
  浇: 'tưới/giội/dội',
  浊: 'trọc/đục/bẩn',
  测: 'đo/trắc',
  浑: 'đục/mơ hồ/hồ đồ/thô/tự nhiên',
  浓: 'nồng/đậm đặc/nùng/đặc/dày',
  浙: 'Chiết',
  浚: 'tuấn/đào sâu',
  浡: 'nổi lên',
  浪: 'sóng/lãng',
  浴: 'tắm',
  海: 'biển/hải',
  浸: 'thấm/ngâm',
  涂: 'bôi/đồ',
  消: 'tiêu/tiêu tan',
  涉: 'liên quan/trải qua/vượt',
  涌: 'tuôn ra/trào',
  涎: 'nước bọt/nước miếng',
  涓: 'suối/chọn',
  涕: 'nước mắt',
  涛: 'đào/sóng/sóng lớn/',
  涝: 'úng lụt',
  涟: 'liên/sóng gợn',
  涡: 'cơn xoáy',
  涧: 'khe',
  涨: 'trướng/phồng',
  涩: 'chát chát',
  涮: 'xuyến/rửa',
  涸: 'cạn/hạc',
  淀: 'điến/lắng đọng',
  淋: 'xối',
  淌: 'trôi/chảy',
  淘: 'đãi/vo/nghịch',
  淡: 'nhạt/đạm',
  淤: 'ứ/ứ đọng',
  淬: 'tôi/ngâm',
  淮: 'Hoài/hoài',
  深: 'sâu',
  混: 'hỗn/lăn lộn/trộn lẫn/lăn lộn',
  淹: 'chìm',
  添: 'thêm/thiêm',
  清: 'thanh/trong/rõ ràng/sạch',
  渍: 'nước đọng',
  渎: 'khinh',
  渐: 'dần/dần dần/tiệm',
  渔: 'cá',
  渗: 'thấm',
  渝: 'du/Du - Tứ Xuyên',
  渠: 'mương/kênh mương',
  渡: 'độ/chở/sang',
  渣: 'cặn bã/tra/mẩu vụn/mảnh vụn',
  渤: 'Bột Hải',
  渥: 'ướt át',
  温: 'ấm/ôn/hâm nóng',
  游: 'du lịch/bơi/du',
  渺: 'miểu/mịt mù',
  湘: 'Tương',
  湦: 'sinh',
  湫: 'tưu/thấp trũng hồ nước',
  湮: 'yên/nhân',
  湾: 'vịnh',
  湿: 'ẩm ướt/thấp/ướt',
  溃: 'bại',
  溅: 'tung tóe/tiên/bắn tung tóe',
  溜: 'trượt/lưu/chuồn mất/dải/chạy',
  溢: 'tràn/tràn đầy/dật',
  溪: 'suối',
  溯: 'ngược dòng/tố',
  溶: 'tan/dung',
  溺: 'chìm/nịch',
  溼: 'ẩm ướt',
  滋: 'tư/két',
  滑: 'trượt/trợt/trơn trượt',
  滓: 'cặn',
  滔: 'thao/đào/thao thao/mênh mông/đầy rẫy/cuồn cuộn',
  滚: 'lăn/cút/cổn/chảy cuồn cuộn/sôi/lặn đi',
  满: 'đầy',
  滢: 'oánh',
  滤: 'lọc',
  滩: 'bãi/ghềnh/than/thác',
  滴: 'giọt/nhỏ/tích/tích',
  漂: 'phiêu/trôi/nổi/thổi',
  漆: 'sơn/nước sơn',
  漏: 'để lọt/lỗ hổng/rò/lậu',
  漪: 'gợn',
  漫: 'khắp/mạn/tràn đầy/ướt sũng',
  漱: 'thấu',
  漻: 'liêu/liệu',
  潜: 'lẻn/lặn/tiềm',
  潭: 'đầm',
  澄: 'trừng/trong vắt',
  澡: 'tắm',
  濯: 'rửa/trạc',
  瀑: 'thác nước',
  灌: 'rót',
  火: 'lửa/hỏa',
  灯: 'đèn',
  灰: 'tro/xám/bụi/hôi',
  灶: 'lò',
  灼: 'đốt/sáng tỏ/lửa đốt sáng/chước',
  灾: 'tai/tai họa',
  灿: 'rực rỡ',
  炉: 'lô/lò/bếp',
  炊: 'nấu/xuy',
  炒: 'xào/rang',
  炕: 'giường/kháng/khô ráo/nướng/sấy/hé ra/mở ra',
  炖: 'hầm/hầm cách thủy/đôn/cách thủy',
  炙: 'thiêu đốt',
  炬: 'bó đuốc',
  炭: 'than',
  炯: 'long lanh',
  炳: 'bính',
  炷: 'trụ',
  炸: 'nổ/tạc/bùng nổ',
  点: 'điểm/giờ/chút/gật',
  炽: 'rực',
  烀: 'luộc',
  烁: 'nhấp nháy',
  烂: 'nát/thối rữa/lạn/nát vụn',
  烈: 'liệt/cháy mạnh/ác/mạnh',
  烘: 'sấy khô/hồng',
  烙: 'in dấu/nướng',
  烛: 'nến/đèn cầy',
  烟: 'khói/thuốc/yên/thuốc lá',
  烤: 'nướng/khảo/sấy/quay/nướng/sấy',
  烧: 'đốt/sốt/thiêu/nướng/xào/cháy/nấu',
  烩: 'xào/quái/chưng',
  烫: 'bỏng/nóng/sấy/hâm/bị phỏng',
  热: 'nóng/nhiệt/nhiệt nóng',
  烯: 'ankin',
  烹: 'nấu',
  焉: 'chỗ này/chỗ nào/yên',
  焊: 'hàn/hạn',
  焖: 'hầm/muộn',
  焗: 'hấp',
  焚: 'đốt',
  焦: 'tiêu/cháy/sốt ruột/cháy sém/lo lắng',
  然: 'nhưng/không sai/nhiên',
  煅: 'nung',
  煎: 'sắc/rán/pha/sắc thuốc',
  煤: 'than đá',
  煦: 'húc/húc',
  照: 'chiếu/so sánh/noi theo/theo',
  煨: 'nướng/nướng (lò nóng)',
  煮: 'nấu/chử/đun/luộc',
  煲: 'nấu/nồi',
  煸: 'kích',
  熄: 'tắt',
  熊: 'gấu/hùng',
  熏: 'hun',
  熔: 'dung/nấu chảy',
  熙: 'hi/rộn ràng',
  熟: 'quen/chín/thục/thục (quen thuộc)',
  熨: 'ủi',
  熬: 'chịu/nấu/ngao/rang khô',
  熵: 'entropy',
  燃: 'đốt',
  燊: 'thân',
  燎: 'cháy/liệu',
  燥: 'khô/táo',
  爪: 'trảo/móng',
  爬: 'bò/ba/gãi/cào',
  爱: 'yêu/ái/thích/tình yêu',
  爲: 'vì/vi',
  爵: 'tước/cốc ba chân',
  父: 'cha/phụ',
  爸: 'cha/ba',
  爹: 'cha/đa',
  爽: 'thoải mái/sảng khoái',
  片: 'phiến/mảnh',
  版: 'bản/hãy',
  牌: 'bài/nhãn hiệu',
  牙: 'răng/nha',
  牛: 'trâu/ngưu/bò',
  牠: 'nó',
  牢: 'lao/bền vững/nhà tù/tù',
  牵: 'dắt/khiên',
  特: 'đặc biệt/đặc/đặc (biệt)/rất',
  犁: 'cày/lê',
  犊: 'nghé/độc',
  犬: 'khuyển/chó',
  状: 'trạng/hình dáng',
  犷: 'hung ác',
  犸: 'voi ma mút',
  犹: 'còn/vẫn còn',
  犼: 'hống/Hống',
  狁: 'duẫn',
  狂: 'cuồng/điên cuồng',
  狎: 'suồng sã/cặp kè/hiệp',
  狐: 'hồ/cáo',
  狗: 'chó/cẩu/con chó',
  狞: 'dữ tợn',
  狠: 'hung ác/ngoan/ngận/tàn nhẫn',
  狩: 'săn/thú',
  狭: 'hẹp',
  狸: 'ly/báo',
  狼: 'sói/lang',
  猊: 'sư tử',
  猎: 'săn/liệp',
  猛: 'mãnh/mãnh liệt',
  猜: 'đoán/sai/ngờ',
  猝: 'bất ngờ',
  猡: 'lợn',
  猥: 'hèn',
  猪: 'heo/lợn/trư',
  猫: 'mèo/miêu',
  猴: 'khỉ/hầu',
  猿: 'vượn',
  獐: 'hoẵng',
  獾: 'chồn',
  玩: 'chơi/đùa/ngoạn',
  玫: 'hồng/đẹp',
  环: 'vòng/hoàn',
  现: 'hiện/xuất hiện',
  玷: 'điếm/làm bẩn',
  玺: 'tỉ/tỉ (ngọc tỉ)',
  玻: 'kính',
  珝: 'hủ/hứa',
  班: 'ban/lớp',
  球: 'cầu/bóng',
  理: 'lý/để ý',
  琍: 'lợi',
  琢: 'mài/dũa',
  琴: 'đàn/cầm/Gin',
  瑰: 'côi/hồn/hồn',
  瑶: 'dao/ngọc',
  瓜: 'dưa/qua',
  瓢: 'bầu/hồ lô',
  瓣: 'cánh/múi/biện/cánh hoa',
  瓦: 'ngói/miếng ngói/watt',
  瓮: 'vò/vò gốm/hủ',
  瓷: 'sứ',
  瓿: 'bẫu/vò/bình',
  甑: 'nồi đất',
  甘: 'cam/ngọt',
  甚: 'rất/cái gì/quá mức/rất : gì',
  甜: 'ngọt/điềm',
  生: 'sinh/sống/',
  甥: 'sinh/cháu trai',
  用: 'dùng/dụng/cần',
  甩: 'vung/súy/vứt/vẫy/bỏ rơi',
  甪: 'lục',
  甫: 'vừa/phủ',
  甭: 'khỏi phải/khỏi',
  田: 'ruộng/điền',
  由: 'từ/do/tùy/bởi',
  甲: 'giáp/A',
  画: 'họa/vẽ/bức tranh/họa (vẽ)/tranh',
  畏: 'sợ',
  畔: 'bờ/bên',
  略: 'hơi/sơ lược/lược',
  番: 'phiên/lần',
  畴: 'trù/dự định',
  畸: 'cơ/ki',
  疚: 'day dứt',
  疤: 'sẹo',
  疮: 'đau nhức/loét',
  疯: 'điên',
  疲: 'mệt/mỏi mệt',
  疼: 'đau/thương yêu/đông',
  疾: 'tật/nhanh',
  痂: 'vảy',
  痊: 'hết bệnh',
  痒: 'ngứa/nhột/dương/ốm',
  痕: 'ngấn/vết',
  痛: 'đau nhức/đau/thương',
  痞: 'du côn',
  痣: 'nốt ruồi',
  痿: 'liệt/nuy',
  瘆: 'hãi',
  瘦: 'gầy/sấu',
  瘪: 'xẹp/quắt',
  瘫: 'co quắp/than/tê liệt',
  瘵: 'ốm',
  瘾: 'nghiện',
  癌: 'ung thư',
  癒: 'dũ/khỏi ốm/lành bệnh',
  癖: 'đam mê/thích',
  登: 'trèo lên/đăng',
  白: 'trắng/bạch/phí công',
  百: 'trăm/bách',
  皆: 'đều/đều là/giai/toàn là/cũng/tất cả',
  皇: 'hoàng/Hoàng',
  皎: 'sáng/kiểu',
  皓: 'sáng/trắng bóc',
  皖: 'Hoàn',
  皮: 'da/lì lợm/vỏ/lì',
  皱: 'nhăn/mặt nhăn/cau',
  皿: 'mãnh/bồn',
  盃: 'cúp',
  盈: 'doanh/đầy đủ',
  盋: 'chén bát',
  盏: 'ngọn/chén nhỏ/ngọn đèn',
  盐: 'muối',
  监: 'giám/giam',
  盒: 'hộp',
  盔: 'nón trụ',
  盖: 'đóng/che/đắp/nắp',
  盗: 'cướp/trộm/đạo',
  盘: 'bàn/cuộn/mâm',
  盛: 'thịnh/đựng',
  目: 'mắt/mục/con mắt',
  盯: 'chằm chằm/trành/nhìn chăm chú/nhìn chòng chọc',
  盲: 'mù/đui mù',
  直: 'thẳng',
  相: 'tướng/cùng nhau/lẫn nhau/tương',
  盹: 'chợp mắt/ngủ gật',
  盼: 'trông mong/phán',
  盾: 'thuẫn/lá chắn',
  省: 'bớt/tỉnh/tiết kiệm',
  眇: 'mù',
  眉: 'lông mày',
  看: 'nhìn/khán/xem',
  眙: 'dị',
  真: 'thật/thực/chân',
  眠: 'ngủ',
  眦: 'khóe mắt',
  眨: 'nháy/trát/nháy mắt',
  眯: 'híp mắt',
  眶: 'vành mắt',
  眸: 'mắt/con mắt/mâu/con ngươi mắt',
  眺: 'ngắm/nhìn',
  眼: 'mắt/nhãn',
  着: 'lấy/mắng',
  睁: 'trợn',
  睇: 'liếc/thê',
  睐: 'liếc/lãi',
  睛: 'con ngươi',
  睡: 'ngủ/thụy',
  睥: 'liếc/bễ',
  睦: 'hòa thuận',
  睬: 'không hỏi',
  睹: 'thấy/đổ/thấy',
  瞄: 'ngắm/miểu',
  瞅: 'nhìn',
  瞎: 'mù/mò mẫm',
  瞒: 'giấu/giấu diếm/man/lừa gạt/dấu diếm',
  瞟: 'nghiêng mắt nhìn',
  瞠: 'trợn/xanh',
  瞥: 'liếc/lườm/miết/liếc về',
  瞧: 'nhìn/tiều/trông trộm/coi',
  瞬: 'giây lát/trong nháy mắt',
  瞳: 'đồng/đồng tử',
  瞻: 'xem',
  矢: 'mũi tên/tiễn',
  矣: 'vậy/rồi',
  知: 'biết/tri',
  矩: 'cự/củ',
  短: 'ngắn/đoản',
  矮: 'thấp/ải/lùn',
  石: 'thạch/đá',
  矶: 'ki/mỏm đá/ki',
  矾: 'phèn',
  矿: 'mỏ',
  砀: 'nãng',
  码: 'mã/ngựa/yard/con ngựa/gõ',
  砂: 'cát/sa',
  砌: 'xây/thế',
  砍: 'chặt/khảm/chém',
  砖: 'gạch/cục gạch',
  砚: 'nghiễn/nghiên mực',
  砟: 'cứng',
  砬: 'lạp/đá',
  砰: 'phanh/ầm/bịch/phịch',
  砵: 'Đồng Bát',
  砸: 'nện/tạp/đập bể/đập',
  砹: 'Astatine',
  砻: 'xay lúa',
  砾: 'đá sỏi',
  硅: 'silic',
  硌: 'cấn',
  硕: 'to lớn',
  硫: 'lưu huỳnh/lưu',
  硬: 'cứng rắn/cứng rắn (ngạnh)',
  确: 'xác thực',
  碎: 'nát/toái/vỡ/bể/nát tan',
  碑: 'bia',
  碗: 'bát/chén/oản',
  碘: 'i-ốt',
  碟: 'đĩa/cái đĩa/điệp',
  碰: 'đụng/bính/va/chọi/chạm/phanh',
  碱: 'tẩy rửa',
  碳: 'than/cacbon',
  碴: 'cặn bã/tra/gây sự',
  碾: 'ép/nghiền',
  磅: 'bang/pound',
  磊: 'lỗi/chồng chất',
  磕: 'đập/dập đầu',
  磙: 'quả lăn',
  磨: 'mài/ma',
  磻: 'Bàn Khê',
  礁: 'đá ngầm san hô',
  示: 'bày ra',
  礽: 'nhưng/Nhưng',
  祁: 'kỳ/Kỳ',
  祂: 'Thần/hắn',
  祈: 'cầu/kỳ/',
  祉: 'chỉ/Chỉ',
  祐: 'hữu/Hữu',
  祛: 'khử/trừ bỏ',
  祟: 'túy/ma',
  祢: 'nễ/họ Nễ',
  祥: 'tường/Tường',
  票: 'phiếu/vé/phiếu vé',
  祯: 'trinh/Trinh',
  祷: 'đảo/cầu khẩn',
  祺: 'kỳ/Kỳ',
  禁: 'cấm',
  禄: 'lộc/Lộc',
  禑: 'Từ',
  禔: 'đề/Đề',
  禛: 'chân/Chân',
  禤: 'huyên/Huyên',
  禩: 'tự/Tự',
  离: 'cách/rời/ly',
  禽: 'chim/cầm',
  禾: 'mạ/lúa',
  秀: 'tú/thanh tú',
  秃: 'trọc/hói/ngốc',
  秆: 'thân/cán',
  秉: 'nắm/bỉnh',
  秋: 'thu/thời kì',
  种: 'loại/trồng/chủng/gan/giống',
  秒: 'giây/miểu',
  租: 'thuê/tô/cho thuê/mướn',
  秤: 'cái cân/cân',
  称: 'xưng/hiệu/danh hiệu/cân',
  秸: 'cành cây',
  移: 'dời',
  稀: 'hiếm',
  稍: 'hơi/sảo/chút',
  稚: 'trẻ con/trĩ',
  稜: 'oai hùng',
  稠: 'nhiều',
  稻: 'cây lúa',
  稼: 'trồng trọt',
  稿: 'bản thảo',
  究: 'cứu',
  穷: 'nghèo/cùng',
  空: 'không/khoảng trống/khoảng không/vô ích/rảnh/trống',
  穿: 'xuyên/mặc',
  窃: 'trộm',
  窄: 'hẹp/chật vật',
  窑: 'lò/hầm lò/chỗ trú',
  窒: 'tắc nghẽn',
  窖: 'hầm',
  窗: 'cửa sổ/song',
  窘: 'quẫn/(túng) quẫn',
  窜: 'vọt/tháo chạy/lủi',
  窝: 'ổ',
  窟: 'quật/hang',
  窥: 'dòm/dòm ngó',
  竂: 'lều',
  立: 'lập/đứng',
  竖: 'dựng thẳng',
  站: 'đứng/trạm',
  竞: 'cạnh/lại còn',
  竟: 'lại/mà/cánh/ắt/rốt cuộc/nhất định/cuối cùng/càng',
  竣: 'tuấn',
  端: 'đầu/bưng/mang/đoan',
  笃: 'đốc/soạt',
  笈: 'tráp/cấp',
  笋: 'măng',
  笑: 'cười/tiếu',
  笙: 'sênh/sinh',
  笞: 'quất/si',
  笠: 'nón lá',
  笨: 'đần/bổn/ngu/dốt',
  第: 'thứ',
  笼: 'cái lồng',
  等: 'chờ/các/các loại/mấy người/mấy/bằng/mấy cái/vân vân',
  筋: 'gân',
  筏: 'bè/phiệt',
  筐: 'giỏ',
  筑: 'trúc/xây',
  筒: 'ống/đồng',
  筵: 'tiệc lễ',
  筷: 'đũa',
  签: 'ký/lá thăm',
  简: 'giản/giản đơn',
  箍: 'quấn/đai/siết/cô',
  箐: 'tinh/thiến',
  箒: 'Houki/trửu',
  箕: 'ki',
  算: 'tính/toán/tính toán/coi là',
  管: 'quản/ống',
  箧: 'tráp/khiếp',
  箩: 'sọt/la',
  箭: 'tiễn/mũi tên/tiến',
  箱: 'rương/hòm',
  箸: 'đũa/trứ',
  篇: 'thiên/quyển sách',
  篓: 'cái sọt',
  篝: 'cái lồng',
  篮: 'rổ/cái giỏ/giỏ',
  篷: 'bồng/cột buồm/mui thuyền',
  簇: 'đám/bụi',
  簧: 'lò xo',
  簪: 'trâm/Kanzashi',
  簸: 'sàng',
  簿: 'sổ ghi chép',
  米: 'gạo/mét/mễ (m)/mễ/thước',
  类: 'loại/tương tự/thứ/giống như',
  籽: 'tử/hạt/hạt giống',
  粉: 'phấn/fan/bún/hồng/bột',
  粒: 'hạt/lạp/viên',
  粗: 'thô/to',
  粘: 'dính',
  粟: 'túc/túc (hạt kê)',
  粤: 'Quảng Đông/Việt(quảng đông)',
  粥: 'cháo',
  粪: 'phân/cứt/phẩn',
  粮: 'lương/lương thực',
  糅: 'hỗn tạp',
  糉: 'tống',
  糊: 'dán/hồ/cháy',
  糕: 'bánh ngọt',
  糖: 'đường/kẹo/đường kẹo',
  糗: 'khứu/bựa vãi',
  糙: 'cẩu thả/tháo',
  糜: 'cháo',
  糟: 'hỏng bét/tao/nát',
  系: 'hệ/thắt',
  紊: 'rối',
  素: 'làm/tố/món chay',
  紧: 'gấp/chặt/nhanh',
  紫: 'tử/tím/Yukari',
  紮: 'ôm/kẹp/cột',
  累: 'mệt mỏi/luy/mệt',
  絮: 'nhứ/sợi thô',
  纠: 'sửa chữa',
  纡: 'quanh co',
  红: 'đỏ/hồng',
  约: 'hẹn/ước/ước chừng',
  级: 'cấp/bậc',
  纯: 'thuần/tinh khiết',
  纰: 'lỗi/lầm',
  纵: 'tung/túng',
  纷: 'lộn xộn',
  纸: 'giấy/chỉ/tử',
  纹: 'văn/vân',
  纺: 'tơ lụa',
  线: 'tuyến/dây/đường/sợi dây',
  细: 'mảnh/tế',
  织: 'dệt/chức/SHIKI/đan',
  终: 'cuối cùng/hết/chung',
  绊: 'vấp',
  经: 'trải qua/kinh',
  绑: 'buộc/trói',
  绕: 'quấn/nhiễu/cuộn/ôm trọn/lượn quanh',
  绘: 'vẽ',
  给: 'cho/cấp/bị',
  绛: 'giáng/đỏ thẫm',
  绞: 'giảo/xoắn/vắt',
  绢: 'lụa',
  绣: 'thêu',
  续: 'tục/tiếp theo',
  绮: 'khinh',
  绳: 'dây thừng',
  维: 'duy/chiều/chiều không gian',
  绷: 'kéo căng/băng bó/banh',
  绸: 'lụa',
  绺: 'túm',
  绽: 'phun/trán',
  绾: 'quán',
  绿: 'lục/xanh biếc/xanh',
  缀: 'xuyết',
  缅: 'xa',
  缎: 'gấm',
  缓: 'chậm/trì hoãn/hoãn',
  缕: 'sợi',
  编: 'biên/bện',
  缗: 'xâu',
  缘: 'duyên/duyến',
  缚: 'trói/trói buộc',
  缝: 'khe hở/vá/may',
  缠: 'quấn/triền/dây dưa',
  缢: 'treo cổ',
  缥: 'phiêu',
  缩: 'co lại/lui',
  缭: 'quấn',
  缴: 'giao nộp',
  缸: 'vạc/vại',
  缺: 'thiếu/khuyết',
  罐: 'bình/lon',
  网: 'lưới/net/võng/ NET/mạng',
  罕: 'hi hữu',
  罗: 'la/lưới',
  罘: 'chúng',
  罢: 'thôi/xong/bỏ đi',
  罩: 'che đậy/tráo/cái lồng',
  罪: 'tội/khổ',
  置: 'đưa/mua/trí',
  羁: 'bó',
  羊: 'dê',
  美: 'đẹp/mỹ',
  羔: 'cừu con',
  羞: 'xấu hổ/thẹn thùng/nhục',
  羡: 'ao ước',
  群: 'bầy/đàn/nhóm/quần',
  羧: 'các-bô-xít cooh',
  翅: 'cánh',
  翔: 'liệng/bay liệng',
  翘: 'vểnh/vểnh lên/kiều',
  翟: 'địch/Trạch (họ)',
  翠: 'thúy/Midori',
  翻: 'lật/trở mình',
  翼: 'cánh/dực',
  考: 'kiểm tra/thi/khảo thi',
  者: 'người/giả/cái',
  而: 'mà',
  耍: 'đùa nghịch/đùa giỡn/đùa bỡn',
  耐: 'nhịn',
  耕: 'cày/canh',
  耗: 'hao tổn',
  耧: 'máy gieo hạt',
  耳: 'tai/mà thôi',
  耶: 'a/cũng/ư',
  耸: 'đứng thẳng',
  耻: 'hổ thẹn',
  耽: 'kéo dài/đam',
  聂: 'Nhiếp/Niếp',
  聊: 'trò chuyện/tán gẫu',
  聋: 'điếc',
  聘: 'mời/sính',
  聚: 'tụ/họp/xóm',
  聪: 'thông/thính giác',
  聿: 'duật/họ',
  肉: 'thịt',
  肋: 'sườn/(sườn) lôi thôi',
  肖: 'tiêu/giống như',
  肘: 'khuỷu tay/khửu tay',
  肚: 'bụng/dạ dày',
  肛: 'giang/chống/hậu môn',
  肝: 'lá gan/can/gan',
  肠: 'ruột/tràng',
  股: 'cỗ/cổ/luồng/đùi/sợi/dòng/cổ phần',
  肤: 'da',
  肥: 'mập',
  肩: 'vai/kiên',
  肯: 'chịu/khẳng/đồng ý/tán thành/bằng lòng',
  肱: 'quăng/cánh tay',
  肴: 'đồ ăn',
  肺: 'phổi',
  肿: 'sưng',
  胁: 'uy hiếp/hiếp',
  胃: 'dạ dày',
  胆: 'gan/đảm/mật/can đảm/Can đảm',
  背: 'cõng/lưng/khiêng/bối/sau lưng/đọc/kém/học thuộc',
  胖: 'béo/mập',
  胭: 'son',
  胯: 'hông/khố/háng',
  胴: 'thân mình',
  胸: 'ngực/hung',
  能: 'có thể/năng/có thể/năng lực',
  脂: 'son/mỡ',
  脆: 'giòn',
  脊: 'sống lưng/sống',
  脏: 'bẩn/tạng',
  脐: 'tề/rốn/yếm cua',
  脓: 'mủ/nùng: mủ',
  脖: 'cái cổ',
  脚: 'chân/cước',
  脯: 'mứt',
  脱: 'thoát/cởi',
  脸: 'mặt/kiểm/khuôn mặt/vẻ mặt/sắc mặt/biểu cảm',
  腆: 'ưỡn',
  腋: 'nách',
  腌: 'ướp/yêm',
  腐: 'mục nát/hủ',
  腕: 'cổ tay/oản',
  腚: 'mông/đít',
  腥: 'tanh',
  腮: 'má/mang/quai hàm',
  腰: 'eo/thắt lưng',
  腴: 'mập/du',
  腹: 'bụng',
  腻: 'dính/ngán/chán',
  腿: 'chân',
  膊: 'cánh tay',
  膘: 'phiêu/mỡ',
  膛: 'thân/lồng ngực/thang/ngực',
  膜: 'màng',
  膝: 'đầu gối/đầu gối',
  膣: 'âm đạo',
  膻: 'mùi/thiên',
  臀: 'mông',
  臂: 'cánh tay',
  臆: 'ức/ý nghĩ/ngực',
  臊: 'thẹn/tao',
  自: 'từ/tự/đương nhiên/tự thân/tự nhiên',
  臭: 'thối',
  至: 'đến/tới/chí',
  致: 'gây nên/gửi tới/dồn',
  臻: 'đạt đến',
  舀: 'múc/cầm',
  舂: 'giã',
  舅: 'cậu',
  舌: 'lưỡi',
  舍: 'bỏ/xá',
  舐: 'liếm',
  舔: 'liếm',
  舞: 'múa/vũ/võ',
  舟: 'thuyền',
  舫: 'phảng/thuyền',
  般: 'bàn/giống như/vậy',
  舱: 'khoang thuyền/khoang',
  舵: 'đà/tay lái',
  舶: 'thuyền đi biển',
  舷: 'mạn thuyền',
  艇: 'thuyền/tàu',
  艘: 'chiếc/chiến thuyền',
  良: 'lương/người lương thiện',
  艳: 'diễm/tươi đẹp',
  节: 'tiết/lễ/knot',
  芒: 'mang/mũi nhọn',
  花: 'hoa/tiêu/tiêu xài/tốn',
  芽: 'mầm/mầm mỏ',
  苔: 'rêu',
  苗: 'mầm/miêu',
  苛: 'hà khắc/hà',
  苟: 'cẩu/cẩu thả',
  苣: 'rau diếp',
  若: 'như/nếu',
  苦: 'khổ/đắng',
  茂: 'mậu/tốt',
  茄: 'cà',
  茎: 'thân/hành',
  茔: 'oanh/phần',
  茗: 'minh/trà',
  茜: 'thiến/Tây/Akane',
  茧: 'kén/vết chai/kén',
  茬: 'gốc rạ/mảnh vụn (gốc)',
  茵: 'đệm/đệm',
  荀: 'Tuân/tuần',
  荆: 'gai/Kinh',
  草: 'cỏ/cây cỏ/thảo',
  荒: 'hoang/Hoang',
  荣: 'vinh/quang vinh',
  荤: 'ăn mặn',
  荫: 'ấm/bóng râm',
  荮: 'bọc bằng cỏ',
  药: 'thuốc/dược',
  莓: 'dâu',
  莠: 'xấu',
  莫: 'chớ/màn/không ai/sờ/mạc',
  莲: 'sen/liên',
  获: 'lấy được',
  莹: 'oánh/óng ánh',
  菇: 'nấm',
  菜: 'đồ ăn/rau/món ăn/thái',
  菠: 'cải bó xôi',
  菲: 'phỉ',
  萃: 'tụ tập/tụy',
  萌: 'manh/moe/nảy sinh (manh)',
  萎: 'héo',
  萘: 'đồ',
  落: 'rơi/lạc',
  葩: 'ba/hoa',
  葫: 'hồ lô',
  葬: 'táng/chôn cất/mai táng',
  葱: 'hành/thông/hành tây',
  葵: 'quỳ/Aoi',
  蒂: 'cuống/đế',
  蒋: 'tưởng/đem',
  蒙: 'được/che/lừa/mê mẩn/đoán mò/mông/ngu dốt/phủ',
  蒜: 'tỏi',
  蒲: 'Bồ',
  蒸: 'chưng/xông',
  蒿: 'hao/cây ngải',
  蓝: 'lam/Ran',
  蓦: 'đột nhiên',
  蓬: 'bồng/oành',
  蔗: 'giá/mía',
  蔫: 'ỉu xìu',
  蔬: 'sơ/rau',
  蔷: 'tường',
  蔽: 'che',
  蕃: 'phiên',
  蕴: 'uẩn/bao hàm',
  蕾: 'nụ/lôi',
  薄: 'mỏng/bạc',
  薅: 'kéo/hao',
  薪: 'củi/lương',
  薯: 'khoai',
  薰: 'huân/hun',
  藏: 'giấu/trốn/cất/tạng/tàng',
  藕: 'ngó sen',
  藤: 'dây leo/đằng',
  蘑: 'ma/nấm',
  蘸: 'chấm/trám',
  虏: 'bắt/bắt làm nô lệ',
  虐: 'ngược/hành hạ',
  虑: 'lo',
  虞: 'ngu/lo lắng',
  虢: 'quắc/Quắc',
  虱: 'rận/sắt',
  虹: 'cầu vồng',
  虽: 'dù/mặc dù',
  虾: 'tôm/hà',
  蚁: 'kiến/con kiến/nghĩ',
  蚊: 'muỗi',
  蚌: 'con trai/con trai(bạng)',
  蚕: 'tằm',
  蚤: 'bọ chét/tảo',
  蚱: 'con ve',
  蚺: 'trăn',
  蛀: 'đục',
  蛆: 'giòi/thư',
  蛇: 'rắn/xà',
  蛊: 'cổ/sâu độc',
  蛋: 'trứng/đản',
  蛏: 'sinh',
  蛐: 'con dế',
  蛙: 'ếch/oa',
  蛛: 'nhện',
  蛟: 'giao/thuồng luồng',
  蛭: 'đỉa/điệt',
  蛮: 'rất/man',
  蛰: 'ngủ đông/ẩn nấp',
  蛹: 'kén',
  蜂: 'ong/phong',
  蜃: 'thận/thận (*con trai)',
  蜇: 'đốt/triết',
  蜘: 'tri/nhện',
  蜡: 'sáp/đèn cầy',
  蜢: 'châu chấu/mãnh',
  蜥: 'thằn lằn/rắn mối',
  蜷: 'cuộn tròn/quyền',
  蝇: 'ruồi/dăng',
  蝉: 've/thiền/con ve',
  蝎: 'bọ cạp/hạt',
  蝠: 'bức/dơi',
  蝮: 'phúc/rắn hổ mang',
  蝶: 'bướm/điệp',
  融: 'tan',
  螫: 'nọc độc',
  螺: 'xoắn ốc/loa',
  蟥: 'đỉa',
  蟹: 'cua/giải',
  蠡: 'lãi',
  蠢: 'xuẩn/ngu xuẩn/ngu',
  蠹: 'mọt/con mọt',
  血: 'máu/huyết',
  行: 'đi/được/hành/nghề/làm/hạnh',
  衔: 'ngậm/hàm/liên tiếp',
  街: 'đường phố/nhai/phố/chợ',
  衡: 'hoành/nhất định',
  衣: 'áo/y',
  补: 'bổ/bù',
  表: 'biểu/đồng hồ/bề ngoài/đơn/bày tỏ',
  衫: 'áo',
  衬: 'lót/sấn',
  衾: 'chăn/khâm',
  袂: 'tay áo/mệ',
  袋: 'túi/xách',
  袖: 'tay áo/tụ',
  袛: 'chi/đê',
  袜: 'vớ',
  被: 'bị/được/chăn',
  袭: 'tập/tập (kích)',
  袯: 'tơi nón',
  裁: 'cắt/tài',
  裂: 'nứt/nứt ra/rách',
  装: 'trang/chứa/giả/lắp/giả bộ/làm ra vẻ/sắp xếp/cài đặt',
  裆: 'háng/đang/đũng quần',
  裘: 'cầu/áo lông',
  裙: 'váy',
  裢: 'hầu bao',
  裤: 'quần',
  裨: 'tì/bì',
  裳: 'váy/Thường',
  裸: 'lõa/trần/khỏa thân',
  褂: 'áo khoác',
  褚: 'chử/Chử',
  褥: 'tấm đệm',
  褪: 'cởi',
  褴: 'rách tả tơi',
  襟: 'vạt áo',
  襮: 'biểu lộ',
  要: 'muốn/yếu/phải/quan trọng/nếu/sắp',
  覆: 'che',
  见: 'thấy/gặp/kiến/xem',
  观: 'xem/quan/quán',
  觅: 'tìm/kiếm/tìm kiếm',
  视: 'xem/thị/nhìn kỹ/coi',
  觉: 'cảm giác/giấc',
  觊: 'mong muốn',
  觑: 'dò xét/nhìn trộm',
  角: 'sừng/vai diễn/góc/giác/nhân vật',
  觜: 'miệng/tuy',
  觞: 'thương/chén',
  解: 'giải/hiểu/am hiểu/mổ',
  触: 'sờ/đụng',
  言: 'nói/ngôn/lời',
  訇: 'oanh/hoanh',
  誓: 'thề',
  説: 'nói/thuyết',
  计: 'kế/tính',
  订: 'đặt trước/đính',
  认: 'nhận thức/nhận',
  讥: 'cơ/mỉa mai',
  讨: 'lấy/đòi',
  让: 'để/nhường/bảo',
  讪: 'ngượng/ngượng ngập',
  讯: 'tin tức/nhanh/tin',
  记: 'nhớ/ghi/ký/cái',
  讲: 'giảng/kể/nói',
  讳: 'húy/kiêng kị',
  讶: 'quái lạ',
  许: 'hứa/cho phép/tán dương/đính hôn',
  讹: 'lừa bịp/ngoa/hạch',
  论: 'luận/nói/bàn về',
  访: 'thăm/tìm hiểu',
  诀: 'quyết/bí quyết',
  证: 'chứng/chứng nhận',
  诂: 'cổ',
  评: 'bình/bình luận',
  诅: 'rủa/trớ',
  识: 'biết/thức',
  诈: 'lừa dối/gạt',
  诊: 'xem bệnh',
  诓: 'lừa gạt/gạt/lừa',
  试: 'thử/thí/thi',
  诗: 'thơ/thi',
  诛: 'tru/giết',
  话: 'lời nói/nói',
  诞: 'sinh/đản',
  询: 'tuân/hỏi ý kiến',
  该: 'nên/cai/cái kia',
  诧: 'sá/kinh ngạc',
  误: 'lầm',
  诳: 'lừa gạt/cuống/nói dối/lừa dối',
  说: 'nói/thuyết',
  诶: 'ài/ấy/ôi chao',
  请: 'mời/xin/thỉnh/xin mời',
  诹: 'trâu/tưu',
  诺: 'nặc/ừm/vâng/dạ',
  读: 'đọc/độc/xem/học',
  谁: 'ai/người đó/người nào/thùy/đó/kẻ đó',
  调: 'điều/giọng',
  谄: 'siểm/nịnh',
  谈: 'đàm/nói/đàm luận',
  谎: 'láo/dối',
  谓: 'vị/gọi là',
  谗: 'thèm/gièm pha',
  谜: 'mê/câu đố',
  谢: 'tạ/tạ ơn/cảm ơn',
  谬: 'sai',
  谯: 'tiêu/tiếu',
  豁: 'thông suốt',
  豉: 'chao/thị',
  豕: 'lợn/con heo',
  象: 'tượng/giống như/voi/giống',
  豢: 'nuôi',
  貂: 'chồn/điêu',
  貉: 'con chồn',
  貘: 'heo vòi',
  负: 'phụ/cõng/thua/âm/cậy/phụ',
  账: 'sổ sách/món nợ',
  货: 'hàng/hóa',
  贩: 'phiến/buôn bán',
  贫: 'bần/lắm mồm/nghèo',
  贬: 'biếm/giáng chức/cách chức',
  购: 'mua/cấu/mua sắm',
  贯: 'xâu/quan/quán',
  贴: 'thiếp/dán',
  贵: 'quý/đắt',
  贷: 'vay',
  贺: 'chúc/hạ',
  贼: 'tặc/trộm/kẻ trộm',
  贾: 'giả/cổ',
  赈: 'cứu tế/giúp',
  赊: 'nợ/xa',
  赌: 'cược/đánh bạc/đổ/đánh cược/đánh cược',
  赎: 'chuộc',
  赏: 'thưởng/phần thưởng/thưởng thức',
  赐: 'ban thưởng/ban cho/thưởng',
  赖: 'lại/ỷ lại/dựa vào/nhờ cậy/vô lại',
  赘: 'vô dụng',
  赚: 'kiếm/lừa/kiếm lời/lợi nhuận',
  赛: 'thi đấu/thắng',
  赞: 'tán/khen',
  赢: 'thắng/doanh',
  赣: 'Cán',
  赤: 'đỏ/xích',
  赧: 'thẹn đỏ mặt',
  赫: 'hách/Hertz',
  赵: 'triệu/Triệu',
  赶: 'đuổi/cản/đưa',
  起: 'lên/khởi/dậy/cái',
  趁: 'thừa dịp/sấn',
  趄: 'nghiêng',
  超: 'siêu/cực kỳ/Chao',
  越: 'càng/vượt/việt',
  趋: 'xu thế',
  趟: 'lội/chuyến',
  足: 'đủ/chân/túc',
  趴: 'nằm sấp/nằm úp sấp',
  趿: 'mang',
  跃: 'vọt/nhảy',
  跄: 'loạng choạng',
  跌: 'ngã/điệt/hạ',
  跑: 'chạy/bào',
  跛: 'cà thọt',
  距: 'cách/cự',
  跟: 'cùng/theo/cân/giống như/như là',
  跨: 'vượt/vượt qua/nhảy qua',
  跪: 'quỳ/quỵ',
  路: 'đường/lộ',
  跳: 'nhảy/khiêu/đập',
  践: 'giẫm đạp/thực hiện',
  跺: 'đập mạnh/giẫm',
  踝: 'mắt cá chân/mắt cá',
  踞: 'ngồi/cứ',
  踢: 'đá/thích',
  踣: 'té ngã',
  踩: 'giẫm/thải/giẫm lên/đạp',
  踮: 'điểm/nhón chân',
  踱: 'bước đi thong thả',
  踹: 'đạp/đoán/đuổi',
  蹂: 'chà đạp',
  蹄: 'vó/đề/móng/chân',
  蹍: 'giẫm',
  蹙: 'nhàu',
  蹚: 'lội/thang',
  蹦: 'nhảy',
  蹬: 'đạp/đặng',
  蹭: 'cọ/chà xát/đi từ từ/chùi/sượt',
  蹲: 'ngồi xổm/ngồi chồm hổm/tồn',
  蹼: 'màng',
  蹾: 'giằng mạnh',
  蹿: 'nhảy lên',
  躁: 'nóng nảy',
  躯: 'thân/thân thể',
  躲: 'tránh/trốn/đóa',
  躺: 'nằm/thảng',
  车: 'xe/xa',
  轮: 'vòng/luân/vành/tua',
  软: 'mềm/nhuyễn',
  轰: 'oanh/ầm',
  轻: 'nhẹ/khinh/khẽ',
  载: 'chở/lại/tái/tải/năm/ghi',
  较: 'so sánh/khá/tương đối',
  辄: 'triếp/thì',
  辆: 'chiếc',
  辇: 'liễn/xe kéo',
  辉: 'huy/sáng chói',
  辍: 'ngừng/xuyết/thôi/nghỉ',
  输: 'thua/vận chuyển/thâu/truyền/nhập',
  辛: 'tân/cực nhọc/',
  辜: 'cô/tội',
  辟: 'tích',
  辣: 'cay/lạt',
  辨: 'phân biệt',
  辰: 'thần/Thìn',
  边: 'bên cạnh/vừa/bên/biên/một bên/phe/cạnh',
  辽: 'Liêu',
  迁: 'dời/thiên',
  迄: 'đến/bèn',
  迅: 'nhanh chóng/tấn',
  过: 'qua/quá/từng/đã từng/tội/sai lầm',
  迈: 'bước/mại',
  近: 'gần/cận',
  返: 'trở lại/phản',
  还: 'còn/trả/hoàn/vẫn/còn chưa',
  这: 'cái này/giá/này/vậy/đây',
  进: 'tiến/vào/tiến vào',
  远: 'xa',
  违: 'làm trái/không tuân/vi',
  连: 'ngay cả/liền/liên/cả/liên tục/nối/đại đội',
  迟: 'trễ/trì',
  迥: 'khác hẳn',
  迫: 'bách/sát/vội vã',
  迸: 'tóe',
  迹: 'dấu vết/tích',
  追: 'truy/đuổi/theo đuổi',
  退: 'lui/thoái/thối/lùi',
  送: 'đưa/tặng/tiễn/tiễn đưa/tống',
  适: 'vừa/thích',
  逃: 'trốn/đào',
  逆: 'nghịch/trái ngược',
  选: 'tuyển/chọn',
  逊: 'kém/tốn',
  逋: 'bỏ trốn',
  递: 'đưa/lần lượt',
  逗: 'đùa/đậu/trêu chọc/buồn cười/đậu',
  逛: 'đi dạo/cuống',
  逝: 'trôi qua',
  速: 'nhanh/tốc/tốc độ',
  逢: 'gặp/phùng',
  逮: 'bắt/bắt bớ',
  逼: 'bức/ép',
  逾: 'hơn/vượt qua',
  遁: 'độn/chui',
  遂: 'liền/thích thú',
  遇: 'gặp/ngộ',
  遍: 'lượt/khắp/biến/lần/khắp cả',
  遐: 'xa',
  遛: 'lưu/dắt',
  遣: 'phái/khiến/khiển/sai',
  遥: 'xa',
  遭: 'bị/lần/tao',
  遮: 'che/chận',
  遴: 'lân',
  避: 'tránh',
  邀: 'mời/yêu cầu/yêu',
  那: 'kia/cái kia/vậy/cái nào/đâu/nào/đó',
  邬: 'ô/ổ',
  邰: 'thai/Thai',
  邵: 'Thiệu',
  邹: 'nhăn/trâu',
  邻: 'lân cận/hàng xóm',
  邽: 'khuê',
  郃: 'hợp',
  郊: 'ngoại ô',
  郎: 'lang/đám/chúng',
  郜: 'cốc',
  郭: 'quách/Quách',
  都: 'đều/cũng/đô/thủ đô',
  鄃: 'huyện du',
  酌: 'rót/chước',
  配: 'phối/xứng',
  酒: 'rượu/tửu',
  酝: 'ủ',
  酥: 'tan chảy/xốp giòn.bánh',
  酱: 'tương/-chan',
  酸: 'chua/đau xót/axit/toan/chua xót/Toan (a-xit)/mệt',
  酿: 'nhưỡng/cất',
  醉: 'say',
  醋: 'dấm/dấm chua/thố',
  醚: 'ê-te',
  醭: 'váng',
  醯: 'dấm/ê',
  醺: 'say/say rượu',
  采: 'hái/khai thác/ngắt/thải',
  釉: 'men/men (gốm, sứ)',
  释: 'thả/thích',
  里: 'bên trong/lý/dặm/trong/ở bên trong',
  重: 'nặng/trọng/trùng',
  量: 'lượng/đo',
  金: 'kim/vàng',
  釜: 'nồi đồng',
  鉴: 'giám/xem cho',
  鎗: 'sinh',
  鑫: 'Hâm',
  钋: 'polonium',
  钓: 'câu/điếu/lưỡi câu',
  钗: 'trâm/sai/thoa cài tóc/trâm (cài tóc)',
  钙: 'canxi',
  钚: 'Plutonium/bất',
  钝: 'cùn/độn',
  钞: 'tiền giấy/sao',
  钟: 'chuông/đồng hồ/chung/chuông / đồng hồ',
  钠: 'Natri',
  钢: 'thép/cương',
  钥: 'chìa/chìa khóa/thược',
  钨: 'vonfram/ô/',
  钩: 'câu/(móc) câu',
  钮: 'nút/tay cầm',
  钱: 'tiền/tiễn',
  钳: 'kìm',
  钸: 'tấm kim loại',
  钻: 'chui/khoan/dùi/xuyên/toản/kim cương',
  钾: 'kali/giáp (Ka)',
  铀: 'Uranium/Urani',
  铁: 'sắt/thiết',
  铂: 'bạch kim',
  铃: 'linh/chuông',
  铅: 'chì',
  铐: 'còng tay',
  铛: 'keng/đang',
  铝: 'nhôm',
  铡: 'trát/trảm',
  铪: 'ha/cáp',
  铬: 'crôm',
  铭: 'minh/chữ khắc',
  铮: 'tranh/loong coong',
  铲: 'xẻng/xúc/xẻng xúc',
  银: 'ngân/bạc',
  铸: 'đúc',
  铺: 'trải/phô/phố/cửa hàng',
  链: 'liên/liệm/liệm dây xích',
  铿: 'khanh/leng keng/lạch cạch/loảng xoảng',
  锁: 'khóa/tỏa',
  锂: 'lithium/lí',
  锄: 'cuốc',
  锅: 'nồi/oa',
  锆: 'zirconium',
  锈: 'gỉ/gỉ',
  锉: 'mài/tỏa',
  锊: 'vén',
  锋: 'phong/mũi',
  锌: 'kẽm',
  锐: 'duệ/sắc nhọn/nhuệ',
  锗: 'Germanium',
  错: 'sai/thác/kém/lỗi',
  锚: 'neo/cái neo/mỏ neo',
  锡: 'tích/thiếc',
  锣: 'la/cái chiêng',
  锤: 'chùy/nện/chuy',
  锥: 'khoan/trùy',
  锦: 'gấm',
  锨: 'hân/xẻng',
  锭: 'thỏi/đĩnh',
  键: 'khóa/chốt',
  锯: 'cưa',
  锰: 'mangan',
  锵: 'bang/thương/cheng/keng/BOANG...',
  锹: 'cái xẻng/thiêu',
  锺: 'đồng hồ/chung',
  锻: 'rèn',
  镀: 'mạ/độ',
  镁: 'Magiê',
  镂: 'lũ/điêu khắc',
  镅: 'Americium',
  镈: 'chiêng',
  镉: 'Cadmium Cd',
  镋: 'đảng/đinh ba',
  镍: 'niken',
  镐: 'hạo/xà beng',
  镑: 'bảng',
  镜: 'kính/gương/Kagami',
  镡: 'đốc kiếm',
  镣: 'xích chân',
  镭: 'Radium',
  镯: 'vòng tay',
  镶: 'khảm/nạm',
  长: 'dài/mọc/trưởng/trường/sinh trưởng/lớn',
  门: 'cửa/môn/cánh cửa/们/khẩu',
  闩: 'then cài',
  闪: 'tránh/lóe/chuồn/nhanh chóng/thiểm/chợt hiện',
  闫: 'diêm/Diêm',
  闭: 'bế/đóng/nhắm',
  问: 'hỏi/vấn',
  闯: 'xông/sấm',
  闲: 'nhàn/rảnh rỗi',
  间: 'ở giữa/gian/đang lúc',
  闷: 'buồn bực/im lìm/muộn/ngạt',
  闸: 'áp/hạp',
  闹: 'náo',
  闺: 'khuê/khuê phòng',
  闻: 'nghe/ngửi/văn',
  阄: 'cưu/cái thăm',
  阉: 'thiến/yêm/hoạn',
  阎: 'Diêm',
  阑: 'ngăn cản',
  阔: 'rộng/khoát/rộng rãi/giàu',
  阖: 'hạp/đóng',
  阪: 'dốc núi',
  防: 'phòng/phòng ngự',
  阶: 'giai/cấp/bậc',
  阻: 'ngăn/ngăn trở',
  降: 'hàng/giảm',
  陕: 'nhanh/thiểm',
  陡: 'đột ngột/xoay mình',
  院: 'viện/sân',
  陨: 'vẫn/rơi',
  陪: 'bồi/cùng/theo/tiếp/đền',
  陶: 'gốm/đào',
  陷: 'hãm/vùi lấp',
  隅: 'góc',
  随: 'theo/tùy',
  隔: 'cách/ngăn',
  隙: 'khe hở',
  隧: 'hang ngầm',
  隼: 'chuẩn/chim cắt/lỗ/Chim Cắt',
  难: 'khó/nan/khó khăn/nạn',
  雁: 'nhạn/ngỗng',
  集: 'tập/(tụ) tập',
  雇: 'thuê/mướn',
  雌: 'thư/con mái/cái',
  雍: 'ung/Ung',
  雎: 'sư',
  雏: 'chim non',
  雨: 'mưa/vũ',
  零: 'số không/0/không/linh/lẻ/không',
  雷: 'lôi/sấm',
  雾: 'sương mù/vụ',
  需: 'cần/nhu',
  霁: 'tễ/nguôi',
  霉: 'nấm mốc',
  霍: 'hoắc/bỗng',
  霎: 'một thoáng',
  霑: 'thấm/nhiễm',
  霭: 'ai/sương',
  霹: 'sấm sét',
  靑: 'giáp',
  青: 'thanh/xanh',
  静: 'tĩnh/Shizuka',
  靛: 'chàm/điện',
  非: 'không phải/phi/không/không phải là',
  靠: 'dựa vào/sát lại/kháo/cập/dựa vào',
  靡: 'mị',
  面: 'mặt/bột/diện/mì',
  靥: 'má lúm đồng tiền/lúm đồng tiền',
  靴: 'giày',
  靶: 'bia/cái bia',
  鞋: 'giày',
  鞍: 'yên',
  鞘: 'vỏ (kiếm, đao)/sao',
  鞣: 'thuộc da',
  鞭: 'roi/cây roi/tiên',
  韧: 'mềm dai/nhận/dẻo dai',
  韩: 'Hàn/hàn',
  韭: 'hẹ/cửu',
  页: 'trang',
  顶: 'đỉnh/đính',
  须: 'cần/râu/tu',
  顾: 'chú ý/ngoảnh đầu/thăm/cố',
  顿: 'bỗng nhiên/ngừng lại/đốn/ngừng/bữa/tấn/trận',
  颅: 'sọ',
  领: 'lĩnh/cổ/dẫn',
  颇: 'có phần/khá',
  颊: 'gò má',
  颌: 'quai hàm',
  颍: 'dĩnh',
  频: 'tần/nhiều lần',
  颓: 'sụt',
  颔: 'hạm/gật đầu',
  颗: 'khỏa/viên/khối',
  题: 'đề/đề tài',
  颚: 'hàm',
  额: 'trán/ngạch/ách',
  颠: 'điên/đỉnh/xóc',
  颢: 'hạo/run',
  颤: 'rung động/chiến/run rẩy',
  颦: 'tần/nhăn mày',
  风: 'gió/phong/phong cách',
  飑: 'tiêu/đua',
  飕: 'sưu/vù/vèo',
  飘: 'phiêu/tung bay/thổi/nhẹ nhàng',
  飙: 'bão tố',
  飞: 'bay/phi/非',
  食: 'ăn/thực',
  餐: 'bữa ăn/món ăn/xan/cơm/món (ăn)/món ăn',
  餔: 'quả khô tẩm đường',
  餠: 'bánh',
  餵: 'cho ăn',
  饕: 'tham ăn/thao',
  饥: 'đói/cơ',
  饭: 'cơm/phạn',
  饮: 'uống/ẩm/đồ uống',
  饱: 'no bụng/ăn no/no',
  饵: 'mồi/mồi',
  饶: 'tha/làm cho/tha cho',
  饷: 'lương/hướng',
  饺: 'sủi cảo',
  饼: 'bánh/bính',
  饽: 'bánh ngọt điểm tâm',
  饿: 'đói/ngạ/đói bụng',
  馅: 'nhân bánh',
  馈: 'quỹ/trấn',
  馊: 'thiu',
  馋: 'thèm/tham',
  馍: 'bánh bao không nhân',
  馎: 'bánh bột',
  首: 'thủ/đầu/bài',
  香: 'hương/thơm/hương thơm/thơm mát',
  马: 'ngựa/mã',
  驮: 'cõng/đà',
  驯: 'thuần',
  驳: 'bác/bác (bỏ)',
  驴: 'con lừa/lừa',
  驶: 'chạy/chạy nhanh',
  驼: 'còng/lạc đà',
  驾: 'giá/điều khiển',
  驿: 'dịch/dịch trạm',
  骂: 'mắng/chửi/mạ',
  骇: 'giật mình/hãi',
  骑: 'cưỡi/kỵ',
  骖: 'tham/ngựa kéo',
  骗: 'lừa gạt/phiến',
  骚: 'tao',
  骛: 'theo đuổi',
  骠: 'phiêu',
  骡: 'la/lừa',
  骤: 'đột nhiên/chợt',
  骧: 'cất cao',
  骨: 'xương/cốt',
  骰: 'xúc xắc/con xúc xắc',
  骸: 'xương cốt',
  髆: 'vai',
  髋: 'xương hông',
  高: 'cao',
  髯: 'râu',
  髻: 'búi tóc',
  鬓: 'tóc mai',
  魆: 'tối om om',
  魇: 'yểm/nói mớ/bóng đè',
  魍: 'Võng',
  魏: 'ngụy/Ngụy',
  魑: 'Si',
  鱼: 'cá/ngư',
  鲌: 'cá thiểu',
  鲍: 'bảo',
  鲜: 'tươi/tiên/quang vinh',
  鲤: 'lý/cá chép',
  鲧: 'Cổn',
  鲨: 'cá mập/sa',
  鳃: 'mang',
  鳄: 'ngạc/ngạc(cá sấu)',
  鳍: 'vây cá',
  鳏: 'góa/quan/góa vợ',
  鳖: 'ba ba/rùa/con ba ba',
  鳝: 'thiện/lươn',
  鳞: 'vảy/lân',
  鸟: 'chim/điểu',
  鸡: 'gà/kê/con gà',
  鸣: 'minh/hót',
  鸥: 'âu/hải âu',
  鸦: 'quạ',
  鸩: 'trấm/chậm',
  鸭: 'vịt/áp',
  鸽: 'bồ câu/chim bồ câu',
  鹁: 'bồ câu nhà',
  鹂: 'Ly/hoàng anh',
  鹅: 'ngỗng/nga/ngan',
  鹊: 'chim khách/thước',
  鹏: 'bằng/Bằng',
  鹑: 'chim cút',
  鹞: 'diều hâu',
  鹰: 'ưng/Ưng',
  鹿: 'hươu',
  麋: 'nai',
  麹: 'đến nỗi',
  麻: 'tê dại/đay/sợi đay/chập choạng/ma',
  麽: 'sao',
  黄: 'hoàng/vàng',
  黏: 'dính',
  黑: 'đen/hắc/hack',
  默: 'mặc/lặng yên',
  黛: 'lông mày',
  黝: 'đen thui',
  黠: 'tinh ranh/hiệt',
  鼋: 'ngoan/ba ba',
  鼓: 'trống/cổ/vỗ',
  鼠: 'chuột',
  鼬: 'chồn sóc/Itachi',
  鼻: 'mũi',
  齐: 'đủ/tề',
  齿: 'răng',
  龊: 'bẩn thỉu',
  龘: 'đát',
  龙: 'rồng/long',
  龛: 'bàn thờ',
  龞: 'ba ba/鳖',
  龟: 'rùa/con rùa/quy',
  ぁ: 'a',
  あ: 'a',
  ぃ: 'i',
  い: 'i',
  う: 'u',
  え: 'e',
  お: 'o',
  か: 'ka',
  が: 'ga',
  き: 'ki',
  ぎ: 'gi',
  く: 'ku',
  ぐ: 'gu',
  け: 'ke',
  げ: 'ge',
  こ: 'ko',
  ご: 'go',
  さ: 'sa',
  ざ: 'za',
  し: 'shi',
  じ: 'ji',
  す: 'su',
  ず: 'zu',
  せ: 'se',
  ぜ: 'ze',
  そ: 'so',
  ぞ: 'zo',
  た: 'ta',
  だ: 'da',
  ち: 'chi',
  つ: 'tsu',
  づ: 'du',
  て: 'te',
  で: 'de',
  と: 'to',
  ど: 'do',
  な: 'na',
  に: 'ni',
  ぬ: 'nu',
  ね: 'ne',
  の: 'no',
  は: 'ha',
  ば: 'ba',
  ぱ: 'ba',
  ひ: 'hi',
  び: 'bi',
  ぴ: 'pi',
  ふ: 'fu',
  ぶ: 'bu',
  ぷ: 'pu',
  へ: 'he',
  べ: 'be',
  ぺ: 'pe',
  ほ: 'ho',
  ぼ: 'bo',
  ぽ: 'po',
  ま: 'ma',
  み: 'mi',
  む: 'mu',
  め: 'me',
  も: 'mo',
  や: 'ya',
  ゆ: 'yu',
  よ: 'yo',
  ら: 'ra',
  り: 'ri',
  る: 'ru',
  れ: 're',
  ろ: 'ro',
  わ: 'wa',
  を: 'wo',
  ん: 'n',
  ア: 'a',
  ィ: 'i',
  イ: 'i',
  ウ: 'u',
  エ: 'e',
  オ: 'o',
  カ: 'ka',
  ガ: 'ga',
  キ: 'ki',
  ク: 'ku',
  グ: 'gu',
  ケ: 'ke',
  コ: 'ko',
  サ: 'sa',
  シ: 'shi',
  ジ: 'ji',
  ス: 'su',
  ズ: 'zu',
  ゼ: 'ze',
  タ: 'ta',
  ダ: 'da',
  チ: 'chi',
  ツ: 'tsu',
  テ: 'te',
  デ: 'de',
  ト: 'to',
  ド: 'do',
  ナ: 'na',
  ニ: 'ni',
  ヌ: 'nu',
  ネ: 'ne',
  ノ: 'no',
  ハ: 'ha',
  バ: 'ba',
  パ: 'pa',
  ヒ: 'hi',
  ビ: 'bi',
  フ: 'fu',
  ブ: 'bu',
  ベ: 'be',
  ペ: 'pe',
  ホ: 'ho',
  ポ: 'po',
  マ: 'ma',
  ミ: 'mi',
  ム: 'mu',
  メ: 'me',
  モ: 'mo',
  ャ: 'ya',
  ョ: 'yo',
  ヨ: 'you',
  ラ: 'ra',
  リ: 'ri',
  ル: 'ru',
  レ: 're',
  ロ: 'ro',
  ワ: 'wa',
  ン: 'n',
  ー: '-',
  ㄅ: 'bao/ba',
  ㄇ: 'sao',
  ㄉ: 'đích',
  ㄊ: 'đột',
  ㄋ: 'nãi/ni',
  ㄌ: 'lực',
  ㄍ: 'cá',
  ㄎ: 'khốc',
  ㄏ: 'phu',
  ㄐ: 'cưu',
  ㄚ: 'nha/a',
  ㄛ: 'ồ',
  ㄜ: 'ách',
  ㄝ: 'dã/đích',
  ㄟ: 'đích',
  ㄡ: 'u',
  ㄣ: 'ân',
  ㄧ: 'một',
  ㄨ: 'W',
  亐: 'tại',
  亱: 'dạ/ban đêm',
  侞: 'Ru',
  俬: 'cụ',
  倄: 'giáo',
  倐: 'chợt',
  勯: 'dan',
  厐: 'lớn',
  吇: 'tử',
  吖: 'a/úi chà',
  吚: 'nha',
  吜: 'chǒu',
  呅: 'miệng nói',
  呡: 'môi',
  呯: 'bình',
  咁: 'như vậy',
  咶: 'thở gấp',
  哐: 'bang/loảng xoảng',
  哴: 'bởi vì thống khổ quá độ mà nghẹn ngào',
  唌: 'đản',
  唎: 'li',
  唦: 'a',
  唲: 'AAAAA',
  啋: 'thái/để ý tới',
  啍: 'đôn',
  啫: 'điệp',
  啲: 'đích',
  喺: 'dính vào',
  嗬: 'ôi',
  嗮: 'sài',
  嘢: 'cũng',
  嚔: 'đế',
  囍: 'hỷ',
  囯: 'quốc',
  坉: 'độn',
  埗: 'khu neo đậu tàu',
  埯: 'yểm',
  変: 'thay đổi',
  姈: 'linh',
  娕: 'hình dạng đẹp',
  娰: 'nữ',
  婓: 'phi',
  媗: 'xuân',
  媜: 'trinh',
  媥: 'piān',
  嫀: 'hạo',
  嫃: 'trinh',
  嫞: 'dung',
  宨: 'tiǎo',
  岀: 'xuất',
  岙: 'Áo',
  嵾: 'sâm',
  庅: 'người',
  庒: 'trang',
  廰: 'sảnh',
  徍: 'vong',
  徫: 'vĩ',
  忈: 'đao',
  忋: 'cái',
  恑: 'ngụy',
  恵: 'Megumi/huệ',
  恾: 'thất kinh',
  悺: 'quan',
  慉: 'sáp',
  懭: 'khoảng',
  戦: 'chiến',
  扽: 'cử động',
  抜: 'bạt',
  抰: 'hiệp',
  抷: 'cụ',
  抺: 'mò',
  挻: 'đỉnh',
  捯: 'đào',
  搯: 'đào',
  摀: 'che',
  擸: 'liệp',
  攎: 'bắt/tóm',
  攞: 'muốn',
  旑: 'y',
  昋: 'quế',
  暪: 'gạt',
  暸: 'khang',
  暼: 'bánh',
  朁: 'tuy',
  柊: 'Hiiragi',
  栔: 'cắt',
  榊: 'Sakaki',
  榍: 'xiè',
  榎: 'giá',
  様: 'dạng',
  槡: 'tang',
  橎: 'fǎn',
  橞: 'cây gỗ',
  欉: 'tùng',
  歩: 'bước',
  気: 'khí',
  沩: 'Viên',
  洢: 'y',
  涴: 'ngâm',
  湳: 'nươm',
  澕: 'hô',
  澘: 'san',
  澪: 'Mio',
  烕: 'diệt',
  煔: 'thiểm',
  牤: 'trâu đực',
  犳: 'trước',
  猀: 'khuyển',
  猭: 'duyên',
  瑫: 'tào/đá đẹp',
  痩: 'gầy',
  眀: 'sáng',
  睋: 'nga',
  睕: 'loan',
  矝: 'lâm',
  砃: 'đá trắng',
  硄: 'quang',
  硾: 'trọng',
  碚: 'bối',
  碦: 'tháp',
  磡: 'xử',
  磳: 'zeng',
  礀: 'tư thế',
  祄: 'Tạ',
  祹: 'Tạo',
  禆: 'khán',
  禟: 'Đường',
  笉: 'tiếu',
  筊: 'giao',
  箂: 'lai',
  粊: 'bỉ',
  粿: 'bánh/gạo cao lương',
  紽: 'đà',
  綑: 'khổn',
  肏: 'thao/địt',
  胘: 'thiết',
  胺: 'án',
  膄: 'thọ',
  膦: 'hợp chất hữu cơ',
  膧: 'mông lung mờ mịt',
  舯: 'trung điểm',
  芠: 'văn',
  芶: 'tán',
  荺: 'quân',
  莤: 'tú',
  萛: 'thu',
  萫: 'soup rau thịt',
  葧: 'nhụy hoa',
  蒍: 'thân cây súng',
  蕼: 'cầm',
  螁: 'ban',
  蠂: 'châu chấu',
  蠎: 'mãng',
  袐: 'bi',
  袓: 'tổ',
  褉: 'hạt',
  覤: 'đối',
  詨: 'hiếu',
  豖: 'con lợn bị cùm',
  賖: 'tha',
  贇: 'xinh đẹp',
  趐: 'sí',
  跆: 'đài',
  踀: 'xước',
  蹱: 'chung/trung',
  躹: 'thân',
  軽: 'khinh',
  郩: 'hào',
  鈃: 'hình',
  鉲: 'Cadium',
  鏕: 'ao',
  鏣: 'tên dụng cụ',
  钐: 'cắt',
  钣: 'bản',
  锃: 'sáng loáng',
  镙: 'máy khí bằng đồng',
  镲: 'sát',
  陃: 'tịnh',
  隡: 'tát',
  雫: 'Shizuku',
  顔: 'nhan',
  顠: 'tóc muối tiêu',
  馞: 'nồng đượm',
  馿: 'lư/con lừa',
  駅: 'nhà ga',
  魭: 'tra',
  鱍: 'cá quẫy đuôi nhảy',
  鱬: 'mặt người thân cá',
  鲅: 'cá thu',
  鸀: 'hắc',
  鹎: 'chim tu ti',
  黙: 'mặc',
  鼑: 'đỉnh',
  齞: 'nhe răng',
  龖: 'đà',
  屁: 'cái rắm',
  姐: 'tỷ',
};
